/*
* Copyright (c) AParovyshnaya 2020-2026
* 
* AParovyshnaya and theirs affiliates make no warranty of any kind
* with regard to this material. 
* 
* AParovyshnaya expressly disclaims all warranties as to the material, express, 
* and implied, including but not limited to the implied warranties of 
* merchantability, fitness for a particular purpose and non-infringement of third 
* party rights. 
* 
* In no event shall AParovyshnaya be liable to you or any other person for any damages, 
* including, without limitation, any direct, indirect, incidental or consequential 
* damages, expenses, lost profits, lost data or other damages arising out of the use, 
* misuse or inability to use the material and any derived software, even if AParovyshnaya, 
* their affiliate or an authorized dealer has been advised of the possibility of such damages. 
* 
*/

export function withLatinNoun5Tests() {
	data.data.push(
		// singular
		{
			"name": "День длинный.",
			"id": "latinN_5_NO_s_49c2faae",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Dies longus est. — День длинный.",
			"test": "<…> Dies longus est. — День длинный.",
		},
		{
			"name": "Вещь новая.",
			"id": "latinN_5_NO_s_20ad9418",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Res nova est. — Вещь новая.",
			"test": "<…> Res nova est. — Вещь новая.",
		},
		{
			"name": "Надежда велика.",
			"id": "latinN_5_NO_s_31cefde0",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Spes magna est. — Надежда велика.",
			"test": "<…> Spes magna est. — Надежда велика.",
		},
		{
			"name": "Вера истинна.",
			"id": "latinN_5_NO_s_439f5b3d",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fides vera est. — Вера истинна.",
			"test": "<…> Fides vera est. — Вера истинна.",
		},
		{
			"name": "Вид прекрасен.",
			"id": "latinN_5_NO_s_1d56ce6a",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Species pulchra est. — Вид прекрасен.",
			"test": "<…> Species pulchra est. — Вид прекрасен.",
		},
		{
			"name": "Лицо радостное.",
			"id": "latinN_5_NO_s_5197848c",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Facies laeta est. — Лицо радостное.",
			"test": "<…> Facies laeta est. — Лицо радостное.",
		},
		{
			"name": "Колесница дня ясная.",
			"id": "latinN_5_GE_s_17f052a3",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Currus diei clarus est. — Колесница дня ясная.",
			"test": "<…> Currus diei clarus est. — Колесница дня ясная.",
		},
		{
			"name": "Природа вещи сложная.",
			"id": "latinN_5_GE_s_2e0fa5d3",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Natura rei complexa est. — Природа вещи сложная.",
			"test": "<…> Natura rei complexa est. — Природа вещи сложная.",
		},
		{
			"name": "Сила надежды крепкая.",
			"id": "latinN_5_GE_s_5010be6",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Virtus spei firma est. — Сила надежды крепкая.",
			"test": "<…> Virtus spei firma est. — Сила надежды крепкая.",
		},
		{
			"name": "Устойчивость веры велика.",
			"id": "latinN_5_GE_s_685f4c2e",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Stabilitas fidei magna est. — Устойчивость веры велика.",
			"test": "<…> Stabilitas fidei magna est. — Устойчивость веры велика.",
		},
		{
			"name": "Форма вида изящная.",
			"id": "latinN_5_GE_s_7daf6ecc",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Forma speciei elegans est. — Форма вида изящная.",
			"test": "<…> Forma speciei elegans est. — Форма вида изящная.",
		},
		{
			"name": "Выражение лица изменчивое.",
			"id": "latinN_5_GE_s_2e5d6d97",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Expressio faciei variabilis est. — Выражение лица изменчивое.",
			"test": "<…> Expressio faciei variabilis est. — Выражение лица изменчивое.",
		},
		{
			"name": "Длина зимнего дня короткая.",
			"id": "latinN_5_GE_s_238e0d81",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Longitudo diei hiemali brevis est. — Длина зимнего дня короткая.",
			"test": "<…> Longitudo diei hiemali brevis est. — Длина зимнего дня короткая.",
		},
		{
			"name": "Полезность вещи величайшая.",
			"id": "latinN_5_GE_s_31221be2",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Utilitas rei maxima est. — Полезность вещи величайшая.",
			"test": "<…> Utilitas rei maxima est. — Полезность вещи величайшая.",
		},
		{
			"name": "Утешение надежды сладостное.",
			"id": "latinN_5_GE_s_377dca04",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Consolatio spei suavis est. — Утешение надежды сладостное.",
			"test": "<…> Consolatio spei suavis est. — Утешение надежды сладостное.",
		},
		{
			"name": "Верность веры известна.",
			"id": "latinN_5_GE_s_728938a9",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fidelitas fidei nota est. — Верность веры известна.",
			"test": "<…> Fidelitas fidei nota est. — Верность веры известна.",
		},
		{
			"name": "Цвет вида разнообразный.",
			"id": "latinN_5_GE_s_21b8d17c",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Color speciei varius est. — Цвет вида разнообразный.",
			"test": "<…> Color speciei varius est. — Цвет вида разнообразный.",
		},
		{
			"name": "Выражение лица радостное.",
			"id": "latinN_5_GE_s_6433a2",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Expressio faciei laeta est. — Выражение лица радостное.",
			"test": "<…> Expressio faciei laeta est. — Выражение лица радостное.",
		},
		{
			"name": "Время дня утреннее.",
			"id": "latinN_5_GE_s_5910e440",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Tempus diei matutinum est. — Время дня утреннее.",
			"test": "<…> Tempus diei matutinum est. — Время дня утреннее.",
		},
		{
			"name": "Сущность вещи скрытая.",
			"id": "latinN_5_GE_s_6267c3bb",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Essentia rei abstrusa est. — Сущность вещи скрытая.",
			"test": "<…> Essentia rei abstrusa est. — Сущность вещи скрытая.",
		},
		{
			"name": "Я принимаю дар дня.",
			"id": "latinN_5_DA_s_533ddba",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Donum diei accipio. — Я принимаю дар дня.",
			"test": "<…> Donum diei accipio. — Я принимаю дар дня.",
		},
		{
			"name": "Забота о вещи необходима.",
			"id": "latinN_5_DA_s_246b179d",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Cura rei necessaria est. — Забота о вещи необходима.",
			"test": "<…> Cura rei necessaria est. — Забота о вещи необходима.",
		},
		{
			"name": "Я желаю помощи надежде.",
			"id": "latinN_5_DA_s_7a07c5b4",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Auxilium spei opto. — Я желаю помощи надежде.",
			"test": "<…> Auxilium spei opto. — Я желаю помощи надежде.",
		},
		{
			"name": "Доверие вере полное.",
			"id": "latinN_5_DA_s_26a1ab54",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fiducia fidei plena est. — Доверие вере полное.",
			"test": "<…> Fiducia fidei plena est. — Доверие вере полное.",
		},
		{
			"name": "Интерес к новому виду возбуждается.",
			"id": "latinN_5_DA_s_3d646c37",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Studium speciei novae excitatur. — Интерес к новому виду возбуждается.",
			"test": "<…> Studium speciei novae excitatur. — Интерес к новому виду возбуждается.",
		},
		{
			"name": "Выражение лица известно.",
			"id": "latinN_5_DA_s_41cf53f9",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Expressio faciei nota est. — Выражение лица известно.",
			"test": "<…> Expressio faciei nota est. — Выражение лица известно.",
		},
		{
			"name": "Хвала дню возносится.",
			"id": "latinN_5_DA_s_5a10411",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Laus diei celebratur. — Хвала дню возносится.",
			"test": "<…> Laus diei celebratur. — Хвала дню возносится.",
		},
		{
			"name": "Охрана вещи тщательная.",
			"id": "latinN_5_DA_s_2ef1e4fa",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Custodia rei diligens est. — Охрана вещи тщательная.",
			"test": "<…> Custodia rei diligens est. — Охрана вещи тщательная.",
		},
		{
			"name": "Утешение надежды предоставляется.",
			"id": "latinN_5_DA_s_306a30c7",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Consolatio spei praestatur. — Утешение надежды предоставляется.",
			"test": "<…> Consolatio spei praestatur. — Утешение надежды предоставляется.",
		},
		{
			"name": "Свидетельство веры даётся.",
			"id": "latinN_5_DA_s_b81eda8",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Testimonium fidei datur. — Свидетельство веры даётся.",
			"test": "<…> Testimonium fidei datur. — Свидетельство веры даётся.",
		},
		{
			"name": "Описание вида точное.",
			"id": "latinN_5_DA_s_68de145",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Descriptio speciei accurata est. — Описание вида точное.",
			"test": "<…> Descriptio speciei accurata est. — Описание вида точное.",
		},
		{
			"name": "Впечатление от лица длится.",
			"id": "latinN_5_DA_s_27fa135a",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Impressio faciei durat. — Впечатление от лица длится.",
			"test": "<…> Impressio faciei durat. — Впечатление от лица длится.",
		},
		{
			"name": "Благодать дня ощутима.",
			"id": "latinN_5_DA_s_46f7f36a",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Gratia diei sensibilis est. — Благодать дня ощутима.",
			"test": "<…> Gratia diei sensibilis est. — Благодать дня ощутима.",
		},
		{
			"name": "Использование вещи частое.",
			"id": "latinN_5_DA_s_421faab1",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Usus rei frequens est. — Использование вещи частое.",
			"test": "<…> Usus rei frequens est. — Использование вещи частое.",
		},
		{
			"name": "Любовь к надежде живучая.",
			"id": "latinN_5_DA_s_2b71fc7e",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Amor spei vivax est. — Любовь к надежде живучая.",
			"test": "<…> Amor spei vivax est. — Любовь к надежде живучая.",
		},
		{
			"name": "Служение вере священное.",
			"id": "latinN_5_DA_s_5ce65a89",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Servitus fidei sacra est. — Служение вере священное.",
			"test": "<…> Servitus fidei sacra est. — Служение вере священное.",
		},
		{
			"name": "Я праздную праздничный день.",
			"id": "latinN_5_AC_s_25f38edc",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Diem solemnem celebro. — Я праздную праздничный день.",
			"test": "<…> Diem solemnem celebro. — Я праздную праздничный день.",
		},
		{
			"name": "Я вижу новую вещь.",
			"id": "latinN_5_AC_s_1a86f2f1",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Rem novam specto. — Я вижу новую вещь.",
			"test": "<…> Rem novam specto. — Я вижу новую вещь.",
		},
		{
			"name": "Я надеюсь на твёрдую надежду.",
			"id": "latinN_5_AC_s_3eb07fd3",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Speram in spem firmam. — Я надеюсь на твёрдую надежду.",
			"test": "<…> Speram in spem firmam. — Я надеюсь на твёрдую надежду.",
		},
		{
			"name": "Я храню святую веру.",
			"id": "latinN_5_AC_s_506c589e",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fidem sanctam servo. — Я храню святую веру.",
			"test": "<…> Fidem sanctam servo. — Я храню святую веру.",
		},
		{
			"name": "Я нахожу редчайший вид.",
			"id": "latinN_5_AC_s_69d0a921",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Speciem rarissimam invenio. — Я нахожу редчайший вид.",
			"test": "<…> Speciem rarissimam invenio. — Я нахожу редчайший вид.",
		},
		{
			"name": "Я хвалю прекрасное лицо.",
			"id": "latinN_5_AC_s_446cdf90",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Faciem pulchram laudo. — Я хвалю прекрасное лицо.",
			"test": "<…> Faciem pulchram laudo. — Я хвалю прекрасное лицо.",
		},
		{
			"name": "Я ожидаю долгий день.",
			"id": "latinN_5_AC_s_799f7e29",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Diem longum exspecto. — Я ожидаю долгий день.",
			"test": "<…> Diem longum exspecto. — Я ожидаю долгий день.",
		},
		{
			"name": "Я приобретаю полезную вещь.",
			"id": "latinN_5_AC_s_4b85612c",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Rem utilem comparo. — Я приобретаю полезную вещь.",
			"test": "<…> Rem utilem comparo. — Я приобретаю полезную вещь.",
		},
		{
			"name": "Я возвещаю твёрдую надежду.",
			"id": "latinN_5_AC_s_277050dc",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Spem certam nuntio. — Я возвещаю твёрдую надежду.",
			"test": "<…> Spem certam nuntio. — Я возвещаю твёрдую надежду.",
		},
		{
			"name": "Я почитаю древнюю веру.",
			"id": "latinN_5_AC_s_5c29bfd",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fidem antiquam colo. — Я почитаю древнюю веру.",
			"test": "<…> Fidem antiquam colo. — Я почитаю древнюю веру.",
		},
		{
			"name": "Я описываю новый вид.",
			"id": "latinN_5_AC_s_7aec35a",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Speciem novam describo. — Я описываю новый вид.",
			"test": "<…> Speciem novam describo. — Я описываю новый вид.",
		},
		{
			"name": "Я вижу печальное лицо.",
			"id": "latinN_5_AC_s_67424e82",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Faciem tristem video. — Я вижу печальное лицо.",
			"test": "<…> Faciem tristem video. — Я вижу печальное лицо.",
		},
		{
			"name": "Они празднуют праздничный день.",
			"id": "latinN_5_AC_s_42110406",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Diem festum celebrant. — Они празднуют праздничный день.",
			"test": "<…> Diem festum celebrant. — Они празднуют праздничный день.",
		},
		{
			"name": "Они восстанавливают потерянную вещь.",
			"id": "latinN_5_AC_s_531d72ca",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Rem perditam recuperant. — Они восстанавливают потерянную вещь.",
			"test": "<…> Rem perditam recuperant. — Они восстанавливают потерянную вещь.",
		},
		{
			"name": "Они испытывают горькую надежду.",
			"id": "latinN_5_AC_s_22d8cfe0",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Spem amaram experiuntur. — Они испытывают горькую надежду.",
			"test": "<…> Spem amaram experiuntur. — Они испытывают горькую надежду.",
		},
		{
			"name": "Я боюсь хрупкой веры.",
			"id": "latinN_5_AC_s_579bb367",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fidem fragilem timeo. — Я боюсь хрупкой веры.",
			"test": "<…> Fidem fragilem timeo. — Я боюсь хрупкой веры.",
		},
		{
			"name": "Мы радуемся ясному дню.",
			"id": "latinN_5_AB_s_1de0aca6",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Diei sereno gaudemus. — Мы радуемся ясному дню.",
			"test": "<…> Diei sereno gaudemus. — Мы радуемся ясному дню.",
		},
		{
			"name": "Мы служим государству (республике).",
			"id": "latinN_5_AB_s_255316f2",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Rei publicae servimus. — Мы служим государству (республике).",
			"test": "<…> Rei publicae servimus. — Мы служим государству (республике).",
		},
		{
			"name": "Я уповаю на твёрдую надежду.",
			"id": "latinN_5_AB_s_41906a77",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Spei certae confisus sum. — Я уповаю на твёрдую надежду.",
			"test": "<…> Spei certae confisus sum. — Я уповаю на твёрдую надежду.",
		},
		{
			"name": "Мы будем повиноваться святой вере.",
			"id": "latinN_5_AB_s_4b9af9a9",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fidei sanctae oboediamus. — Мы будем повиноваться святой вере.",
			"test": "<…> Fidei sanctae oboediamus. — Мы будем повиноваться святой вере.",
		},
		{
			"name": "Мы удивляемся более редкому виду.",
			"id": "latinN_5_AB_s_5387f9e0",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Speciei rarioris miramur. — Мы удивляемся более редкому виду.",
			"test": "<…> Speciei rarioris miramur. — Мы удивляемся более редкому виду.",
		},
		{
			"name": "Мы восхищаемся прекрасным лицом.",
			"id": "latinN_5_AB_s_6e5e91e4",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Faciei pulchrae admiramur. — Мы восхищаемся прекрасным лицом.",
			"test": "<…> Faciei pulchrae admiramur. — Мы восхищаемся прекрасным лицом.",
		},
		{
			"name": "Мы ликуем при восходе дня.",
			"id": "latinN_5_AB_s_2cdf8d8a",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Diei ortu exsultamus. — Мы ликуем при восходе дня.",
			"test": "<…> Diei ortu exsultamus. — Мы ликуем при восходе дня.",
		},
		{
			"name": "Мы верим в истинную вещь.",
			"id": "latinN_5_AB_s_30946e09",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Rei verae credimus. — Мы верим в истинную вещь.",
			"test": "<…> Rei verae credimus. — Мы верим в истинную вещь.",
		},
		{
			"name": "Давайте радоваться будущей надежде.",
			"id": "latinN_5_AB_s_5cb0d902",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Spei futurae gaudeamus. — Давайте радоваться будущей надежде.",
			"test": "<…> Spei futurae gaudeamus. — Давайте радоваться будущей надежде.",
		},
		{
			"name": "Будем упорствовать в католической вере.",
			"id": "latinN_5_AB_s_46fbb2c1",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fidei catholicae perseveremus. — Будем упорствовать в католической вере.",
			"test": "<…> Fidei catholicae perseveremus. — Будем упорствовать в католической вере.",
		},
		{
			"name": "Будем помнить о новом виде.",
			"id": "latinN_5_AB_s_1698c449",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Speciei novae memoriam habeamus. — Будем помнить о новом виде.",
			"test": "<…> Speciei novae memoriam habeamus. — Будем помнить о новом виде.",
		},
		{
			"name": "Ужас уродливого лица.",
			"id": "latinN_5_AB_s_5ef04b5",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Faciei deformis horror est. — Ужас уродливого лица.",
			"test": "<…> Faciei deformis horror est. — Ужас уродливого лица.",
		},
		{
			"name": "Мы подчиняемся жаркому дню.",
			"id": "latinN_5_AB_s_5f4da5c3",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Diei calido obsequimur. — Мы подчиняемся жаркому дню.",
			"test": "<…> Diei calido obsequimur. — Мы подчиняемся жаркому дню.",
		},
		{
			"name": "Мы сосредоточены на трудном деле.",
			"id": "latinN_5_AB_s_443b7951",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Rei difficili intenti sumus. — Мы сосредоточены на трудном деле.",
			"test": "<…> Rei difficili intenti sumus. — Мы сосредоточены на трудном деле.",
		},
		{
			"name": "Мы отчаиваемся от потерянной надежды.",
			"id": "latinN_5_AB_s_14514713",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Spei perditae desperamus. — Мы отчаиваемся от потерянной надежды.",
			"test": "<…> Spei perditae desperamus. — Мы отчаиваемся от потерянной надежды.",
		},
		{
			"name": "Мы свидетели нашей веры.",
			"id": "latinN_5_AB_s_69663380",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fidei nostrae testes sumus. — Мы свидетели нашей веры.",
			"test": "<…> Fidei nostrae testes sumus. — Мы свидетели нашей веры.",
		},
		// plural	
		{
			"name": "Дни зимой короткие.",
			"id": "latinN_5_NO_p_49c2faae",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Dies sunt breves hieme. — Дни зимой короткие.",
			"test": "<…> Dies sunt breves hieme. — Дни зимой короткие.",
		},
		{
			"name": "Новые вещи удивительны.",
			"id": "latinN_5_NO_p_20ad9418",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Res novae sunt mirabiles. — Новые вещи удивительны.",
			"test": "<…> Res novae sunt mirabiles. — Новые вещи удивительны.",
		},
		{
			"name": "Большие надежды нас утешают.",
			"id": "latinN_5_NO_p_31cefde0",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Spes magnae nos consolantur. — Большие надежды нас утешают.",
			"test": "<…> Spes magnae nos consolantur. — Большие надежды нас утешают.",
		},
		{
			"name": "Католические веры едины.",
			"id": "latinN_5_NO_p_439f5b3d",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fides catholicae sunt unanimes. — Католические веры едины.",
			"test": "<…> Fides catholicae sunt unanimes. — Католические веры едины.",
		},
		{
			"name": "Более редкие виды обнаруживаются.",
			"id": "latinN_5_NO_p_1d56ce6a",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Species rariores inveniuntur. — Более редкие виды обнаруживаются.",
			"test": "<…> Species rariores inveniuntur. — Более редкие виды обнаруживаются.",
		},
		{
			"name": "Радостные лица нас радуют.",
			"id": "latinN_5_NO_p_5197848c",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Facies laetae nos gaudent. — Радостные лица нас радуют.",
			"test": "<…> Facies laetae nos gaudent. — Радостные лица нас радуют.",
		},
		{
			"name": "Память о днях долгая.",
			"id": "latinN_5_GE_p_17f052a3",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Memoria dierum longa est. — Память о днях долгая.",
			"test": "<…> Memoria dierum longa est. — Память о днях долгая.",
		},
		{
			"name": "Природа вещей изменчива.",
			"id": "latinN_5_GE_p_2e0fa5d3",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Natura rerum variabilis est. — Природа вещей изменчива.",
			"test": "<…> Natura rerum variabilis est. — Природа вещей изменчива.",
		},
		{
			"name": "Сила надежд крепкая.",
			"id": "latinN_5_GE_p_5010be6",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Virtus sperum firma est. — Сила надежд крепкая.",
			"test": "<…> Virtus sperum firma est. — Сила надежд крепкая.",
		},
		{
			"name": "Устойчивость вер велика.",
			"id": "latinN_5_GE_p_685f4c2e",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Stabilitas fiderum magna est. — Устойчивость вер велика.",
			"test": "<…> Stabilitas fiderum magna est. — Устойчивость вер велика.",
		},
		{
			"name": "Форма видов изящная.",
			"id": "latinN_5_GE_p_7daf6ecc",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Forma specierum elegans est. — Форма видов изящная.",
			"test": "<…> Forma specierum elegans est. — Форма видов изящная.",
		},
		{
			"name": "Выражение лиц изменчивое.",
			"id": "latinN_5_GE_p_2e5d6d97",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Expressio facierum variabilis est. — Выражение лиц изменчивое.",
			"test": "<…> Expressio facierum variabilis est. — Выражение лиц изменчивое.",
		},
		{
			"name": "Длина дней варьируется.",
			"id": "latinN_5_GE_p_238e0d81",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Longitudo dierum variat. — Длина дней варьируется.",
			"test": "<…> Longitudo dierum variat. — Длина дней варьируется.",
		},
		{
			"name": "Полезность вещей величайшая.",
			"id": "latinN_5_GE_p_31221be2",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Utilitas rerum maxima est. — Полезность вещей величайшая.",
			"test": "<…> Utilitas rerum maxima est. — Полезность вещей величайшая.",
		},
		{
			"name": "Утешение надежд сладостное.",
			"id": "latinN_5_GE_p_377dca04",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Consolatio sperum suavis est. — Утешение надежд сладостное.",
			"test": "<…> Consolatio sperum suavis est. — Утешение надежд сладостное.",
		},
		{
			"name": "Верность вер известна.",
			"id": "latinN_5_GE_p_728938a9",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fidelitas fiderum nota est. — Верность вер известна.",
			"test": "<…> Fidelitas fiderum nota est. — Верность вер известна.",
		},
		{
			"name": "Цвет видов разнообразный.",
			"id": "latinN_5_GE_p_21b8d17c",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Color specierum varius est. — Цвет видов разнообразный.",
			"test": "<…> Color specierum varius est. — Цвет видов разнообразный.",
		},
		{
			"name": "Выражение лиц радостное.",
			"id": "latinN_5_GE_p_6433a2",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Expressio facierum laeta est. — Выражение лиц радостное.",
			"test": "<…> Expressio facierum laeta est. — Выражение лиц радостное.",
		},
		{
			"name": "Время дней краткое.",
			"id": "latinN_5_GE_p_5910e440",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Tempus dierum breve est. — Время дней краткое.",
			"test": "<…> Tempus dierum breve est. — Время дней краткое.",
		},
		{
			"name": "Сущность вещей скрытая.",
			"id": "latinN_5_GE_p_6267c3bb",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Essentia rerum abstrusa est. — Сущность вещей скрытая.",
			"test": "<…> Essentia rerum abstrusa est. — Сущность вещей скрытая.",
		},
		{
			"name": "Мы принимаем дары дней.",
			"id": "latinN_5_DA_p_533ddba",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Dona diebus accipimus. — Мы принимаем дары дней.",
			"test": "<…> Dona diebus accipimus. — Мы принимаем дары дней.",
		},
		{
			"name": "Забота о вещах необходима.",
			"id": "latinN_5_DA_p_246b179d",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Cura rebus necessaria est. — Забота о вещах необходима.",
			"test": "<…> Cura rebus necessaria est. — Забота о вещах необходима.",
		},
		{
			"name": "Мы желаем помощи надеждам.",
			"id": "latinN_5_DA_p_7a07c5b4",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Auxilium spes optamus. — Мы желаем помощи надеждам.",
			"test": "<…> Auxilium spes optamus. — Мы желаем помощи надеждам.",
		},
		{
			"name": "Доверие верам полное.",
			"id": "latinN_5_DA_p_26a1ab54",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fiducia fidei plena est. — Доверие верам полное.",
			"test": "<…> Fiducia fidei plena est. — Доверие верам полное.",
		},
		{
			"name": "Интерес к новым видам возбуждается.",
			"id": "latinN_5_DA_p_3d646c37",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Studium speciebus novis excitatur. — Интерес к новым видам возбуждается.",
			"test": "<…> Studium speciebus novis excitatur. — Интерес к новым видам возбуждается.",
		},
		{
			"name": "Выражение лиц известно.",
			"id": "latinN_5_DA_p_41cf53f9",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Expressio faciebus nota est. — Выражение лиц известно.",
			"test": "<…> Expressio faciebus nota est. — Выражение лиц известно.",
		},
		{
			"name": "Мы возносим хвалу дням.",
			"id": "latinN_5_DA_p_5a10411",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Laudes diebus celebramus. — Мы возносим хвалу дням.",
			"test": "<…> Laudes diebus celebramus. — Мы возносим хвалу дням.",
		},
		{
			"name": "Охрана вещей тщательная.",
			"id": "latinN_5_DA_p_2ef1e4fa",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Custodia rebus diligens est. — Охрана вещей тщательная.",
			"test": "<…> Custodia rebus diligens est. — Охрана вещей тщательная.",
		},
		{
			"name": "Утешение надеждам предоставляется.",
			"id": "latinN_5_DA_p_306a30c7",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Consolatio spes praestatur. — Утешение надеждам предоставляется.",
			"test": "<…> Consolatio spes praestatur. — Утешение надеждам предоставляется.",
		},
		{
			"name": "Свидетельства верам даются.",
			"id": "latinN_5_DA_p_b81eda8",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Testimonia fidebus dantur. — Свидетельства верам даются.",
			"test": "<…> Testimonia fidebus dantur. — Свидетельства верам даются.",
		},
		{
			"name": "Описание видов точное.",
			"id": "latinN_5_DA_p_68de145",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Descriptio speciebus accurata est. — Описание видов точное.",
			"test": "<…> Descriptio speciebus accurata est. — Описание видов точное.",
		},
		{
			"name": "Впечатление от лиц длится.",
			"id": "latinN_5_DA_p_27fa135a",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Impressio faciebus durat. — Впечатление от лиц длится.",
			"test": "<…> Impressio faciebus durat. — Впечатление от лиц длится.",
		},
		{
			"name": "Благодать дней ощутима.",
			"id": "latinN_5_DA_p_46f7f36a",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Gratia diebus sensibilis est. — Благодать дней ощутима.",
			"test": "<…> Gratia diebus sensibilis est. — Благодать дней ощутима.",
		},
		{
			"name": "Использование вещей частое.",
			"id": "latinN_5_DA_p_421faab1",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Usus rebus frequens est. — Использование вещей частое.",
			"test": "<…> Usus rebus frequens est. — Использование вещей частое.",
		},
		{
			"name": "Любовь к надеждам живучая.",
			"id": "latinN_5_DA_p_2b71fc7e",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Amor spes vivax est. — Любовь к надеждам живучая.",
			"test": "<…> Amor spes vivax est. — Любовь к надеждам живучая.",
		},
		{
			"name": "Служение верам священное.",
			"id": "latinN_5_DA_p_5ce65a89",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Servitus fidebus sacra est. — Служение верам священное.",
			"test": "<…> Servitus fidebus sacra est. — Служение верам священное.",
		},
		{
			"name": "Мы празднуем праздничные дни.",
			"id": "latinN_5_AC_p_25f38edc",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Dies festos celebramus. — Мы празднуем праздничные дни.",
			"test": "<…> Dies festos celebramus. — Мы празднуем праздничные дни.",
		},
		{
			"name": "Мы видим новые вещи.",
			"id": "latinN_5_AC_p_1a86f2f1",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Res novas spectamus. — Мы видим новые вещи.",
			"test": "<…> Res novas spectamus. — Мы видим новые вещи.",
		},
		{
			"name": "Мы надеемся на твёрдые надежды.",
			"id": "latinN_5_AC_p_3eb07fd3",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "In spes firmas speramus. — Мы надеемся на твёрдые надежды.",
			"test": "<…> In spes firmas speramus. — Мы надеемся на твёрдые надежды.",
		},
		{
			"name": "Мы храним святые веры.",
			"id": "latinN_5_AC_p_506c589e",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fides sanctas servamus. — Мы храним святые веры.",
			"test": "<…> Fides sanctas servamus. — Мы храним святые веры.",
		},
		{
			"name": "Мы находим редчайшие виды.",
			"id": "latinN_5_AC_p_69d0a921",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Species rarissimas invenimus. — Мы находим редчайшие виды.",
			"test": "<…> Species rarissimas invenimus. — Мы находим редчайшие виды.",
		},
		{
			"name": "Мы хвалим прекрасные лица.",
			"id": "latinN_5_AC_p_446cdf90",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Facies pulchras laudamus. — Мы хвалим прекрасные лица.",
			"test": "<…> Facies pulchras laudamus. — Мы хвалим прекрасные лица.",
		},
		{
			"name": "Мы ожидаем долгие дни.",
			"id": "latinN_5_AC_p_799f7e29",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Dies longos exspectamus. — Мы ожидаем долгие дни.",
			"test": "<…> Dies longos exspectamus. — Мы ожидаем долгие дни.",
		},
		{
			"name": "Мы приобретаем полезные вещи.",
			"id": "latinN_5_AC_p_4b85612c",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Res utilis comparamus. — Мы приобретаем полезные вещи.",
			"test": "<…> Res utilis comparamus. — Мы приобретаем полезные вещи.",
		},
		{
			"name": "Мы возвещаем твёрдые надежды.",
			"id": "latinN_5_AC_p_277050dc",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Spes certas nuntiamus. — Мы возвещаем твёрдые надежды.",
			"test": "<…> Spes certas nuntiamus. — Мы возвещаем твёрдые надежды.",
		},
		{
			"name": "Мы почитаем древние веры.",
			"id": "latinN_5_AC_p_5c29bfd",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fides antiquas colimus. — Мы почитаем древние веры.",
			"test": "<…> Fides antiquas colimus. — Мы почитаем древние веры.",
		},
		{
			"name": "Мы описываем новые виды.",
			"id": "latinN_5_AC_p_7aec35a",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Species novas describimus. — Мы описываем новые виды.",
			"test": "<…> Species novas describimus. — Мы описываем новые виды.",
		},
		{
			"name": "Я вижу печальные лица.",
			"id": "latinN_5_AC_p_67424e82",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Facies tristes video. — Я вижу печальные лица.",
			"test": "<…> Facies tristes video. — Я вижу печальные лица.",
		},
		{
			"name": "Они празднуют праздничные дни.",
			"id": "latinN_5_AC_p_42110406",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Dies festa celebrant. — Они празднуют праздничные дни.",
			"test": "<…> Dies festa celebrant. — Они празднуют праздничные дни.",
		},
		{
			"name": "Они восстанавливают потерянные вещи.",
			"id": "latinN_5_AC_p_531d72ca",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Res perditas recuperant. — Они восстанавливают потерянные вещи.",
			"test": "<…> Res perditas recuperant. — Они восстанавливают потерянные вещи.",
		},
		{
			"name": "Они испытывают горькие надежды.",
			"id": "latinN_5_AC_p_22d8cfe0",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Spes amaras experiuntur. — Они испытывают горькие надежды.",
			"test": "<…> Spes amaras experiuntur. — Они испытывают горькие надежды.",
		},
		{
			"name": "Я боюсь хрупких вер.",
			"id": "latinN_5_AC_p_579bb367",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fides fragiles timeo. — Я боюсь хрупких вер.",
			"test": "<…> Fides fragiles timeo. — Я боюсь хрупких вер.",
		},
		{
			"name": "Мы радуемся ясным дням.",
			"id": "latinN_5_AB_p_1de0aca6",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Diebus serenis gaudemus. — Мы радуемся ясным дням.",
			"test": "<…> Diebus serenis gaudemus. — Мы радуемся ясным дням.",
		},
		{
			"name": "Мы служим государственным делам.",
			"id": "latinN_5_AB_p_255316f2",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Rebus publicis servimus. — Мы служим государственным делам.",
			"test": "<…> Rebus publicis servimus. — Мы служим государственным делам.",
		},
		{
			"name": "Мы уповали на твёрдые надежды.",
			"id": "latinN_5_AB_p_41906a77",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Spebus certis confisi sumus. — Мы уповали на твёрдые надежды.",
			"test": "<…> Spebus certis confisi sumus. — Мы уповали на твёрдые надежды.",
		},
		{
			"name": "Мы будем повиноваться святым верам.",
			"id": "latinN_5_AB_p_4b9af9a9",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fidebus sanctis oboediamus. — Мы будем повиноваться святым верам.",
			"test": "<…> Fidebus sanctis oboediamus. — Мы будем повиноваться святым верам.",
		},
		{
			"name": "Мы удивляемся более редким видам.",
			"id": "latinN_5_AB_p_5387f9e0",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Speciebus rarioribus miramur. — Мы удивляемся более редким видам.",
			"test": "<…> Speciebus rarioribus miramur. — Мы удивляемся более редким видам.",
		},
		{
			"name": "Мы восхищаемся прекрасными лицами.",
			"id": "latinN_5_AB_p_6e5e91e4",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Faciebus pulchris admiramur. — Мы восхищаемся прекрасными лицами.",
			"test": "<…> Faciebus pulchris admiramur. — Мы восхищаемся прекрасными лицами.",
		},
		{
			"name": "Мы ликуем в хорошие дни.",
			"id": "latinN_5_AB_p_2cdf8d8a",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Diebus bonis exsultamus. — Мы ликуем в хорошие дни.",
			"test": "<…> Diebus bonis exsultamus. — Мы ликуем в хорошие дни.",
		},
		{
			"name": "Мы верим в истинные вещи.",
			"id": "latinN_5_AB_p_30946e09",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Rebus veris credimus. — Мы верим в истинные вещи.",
			"test": "<…> Rebus veris credimus. — Мы верим в истинные вещи.",
		},
		{
			"name": "Давайте радоваться будущим надеждам.",
			"id": "latinN_5_AB_p_5cb0d902",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Spebus futuris gaudeamus. — Давайте радоваться будущим надеждам.",
			"test": "<…> Spebus futuris gaudeamus. — Давайте радоваться будущим надеждам.",
		},
		{
			"name": "Будем упорствовать в католических верах.",
			"id": "latinN_5_AB_p_46fbb2c1",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fidebus catholicis perseveremus. — Будем упорствовать в католических верах.",
			"test": "<…> Fidebus catholicis perseveremus. — Будем упорствовать в католических верах.",
		},
		{
			"name": "Будем помнить о новых видах.",
			"id": "latinN_5_AB_p_1698c449",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Speciebus novis memoriam habeamus. — Будем помнить о новых видах.",
			"test": "<…> Speciebus novis memoriam habeamus. — Будем помнить о новых видах.",
		},
		{
			"name": "Ужас уродливых лиц.",
			"id": "latinN_5_AB_p_5ef04b5",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Faciebus deformibus horror est. — Ужас уродливых лиц.",
			"test": "<…> Faciebus deformibus horror est. — Ужас уродливых лиц.",
		},
		{
			"name": "Мы подчиняемся жарким дням.",
			"id": "latinN_5_AB_p_5f4da5c3",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Diebus calidis obsequimur. — Мы подчиняемся жарким дням.",
			"test": "<…> Diebus calidis obsequimur. — Мы подчиняемся жарким дням.",
		},
		{
			"name": "Мы сосредоточены на трудных делах.",
			"id": "latinN_5_AB_p_443b7951",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Rebus difficilibus intenti sumus. — Мы сосредоточены на трудных делах.",
			"test": "<…> Rebus difficilibus intenti sumus. — Мы сосредоточены на трудных делах.",
		},
		{
			"name": "Мы отчаиваемся от потерянных надежд.",
			"id": "latinN_5_AB_p_14514713",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Spebus perditis desperamus. — Мы отчаиваемся от потерянных надежд.",
			"test": "<…> Spebus perditis desperamus. — Мы отчаиваемся от потерянных надежд.",
		},
		{
			"name": "Мы свидетели наших вер.",
			"id": "latinN_5_AB_p_69663380",
			"grade": "latin_noun",
			"letters": ["5"],
			"full": "Fidebus nostris testes sumus. — Мы свидетели наших вер.",
			"test": "<…> Fidebus nostris testes sumus. — Мы свидетели наших вер.",
		}
	);
}
