/*
* Copyright (c) AParovyshnaya 2020-2026
* 
* AParovyshnaya and theirs affiliates make no warranty of any kind
* with regard to this material. 
* 
* AParovyshnaya expressly disclaims all warranties as to the material, express, 
* and implied, including but not limited to the implied warranties of 
* merchantability, fitness for a particular purpose and non-infringement of third 
* party rights. 
* 
* In no event shall AParovyshnaya be liable to you or any other person for any damages, 
* including, without limitation, any direct, indirect, incidental or consequential 
* damages, expenses, lost profits, lost data or other damages arising out of the use, 
* misuse or inability to use the material and any derived software, even if AParovyshnaya, 
* their affiliate or an authorized dealer has been advised of the possibility of such damages. 
* 
*/

export function withLatinNoun3Tests() {
	data.data.push(
		// singular
		{
			"name": "Лев обитает в лесу.",
			"id": "latinN_3_NO_s_49c2faae",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Leo in silva habitat. — Лев обитает в лесу.",
			"test": "<…> Leo in silva habitat. — Лев обитает в лесу.",
		},
		{
			"name": "Отец работает в саду.",
			"id": "latinN_3_NO_s_20ad9418",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Pater in horto laborat. — Отец работает в саду.",
			"test": "<…> Pater in horto laborat. — Отец работает в саду.",
		},
		{
			"name": "Корабль стоит в порту.",
			"id": "latinN_3_NO_s_31cefde0",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Navis in portu stat. — Корабль стоит в порту.",
			"test": "<…> Navis in portu stat. — Корабль стоит в порту.",
		},
		{
			"name": "Город велик.",
			"id": "latinN_3_NO_s_439f5b3d",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Urbs magna est. — Город велик.",
			"test": "<…> Urbs magna est. — Город велик.",
		},
		{
			"name": "Ночь тёмная.",
			"id": "latinN_3_NO_s_1d56ce6a",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Nox obscura est. — Ночь тёмная.",
			"test": "<…> Nox obscura est. — Ночь тёмная.",
		},
		{
			"name": "Имя мне известно.",
			"id": "latinN_3_NO_s_5197848c",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Nomen mihi notum est. — Имя мне известно.",
			"test": "<…> Nomen mihi notum est. — Имя мне известно.",
		},
		{
			"name": "Кровь льва красная.",
			"id": "latinN_3_GE_s_17f052a3",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Cruor leonis rubens est. — Кровь льва красная.",
			"test": "<…> Cruor leonis rubens est. — Кровь льва красная.",
		},
		{
			"name": "Любовь отца велика.",
			"id": "latinN_3_GE_s_2e0fa5d3",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Amor patris magnus est. — Любовь отца велика.",
			"test": "<…> Amor patris magnus est. — Любовь отца велика.",
		},
		{
			"name": "Часть корабля сломана.",
			"id": "latinN_3_GE_s_5010be6",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Pars navis fracta est. — Часть корабля сломана.",
			"test": "<…> Pars navis fracta est. — Часть корабля сломана.",
		},
		{
			"name": "Стена города высокая.",
			"id": "latinN_3_GE_s_685f4c2e",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Murus urbis altus est. — Стена города высокая.",
			"test": "<…> Murus urbis altus est. — Стена города высокая.",
		},
		{
			"name": "Тишина ночи страшная.",
			"id": "latinN_3_GE_s_7daf6ecc",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Silentium noctis terribile est. — Тишина ночи страшная.",
			"test": "<…> Silentium noctis terribile est. — Тишина ночи страшная.",
		},
		{
			"name": "Начало имени длинное.",
			"id": "latinN_3_GE_s_2e5d6d97",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Initium nominis longum est. — Начало имени длинное.",
			"test": "<…> Initium nominis longum est. — Начало имени длинное.",
		},
		{
			"name": "Страх льва не велик.",
			"id": "latinN_3_GE_s_238e0d81",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Timor leonis magnus non est. — Страх льва не велик.",
			"test": "<…> Timor leonis magnus non est. — Страх льва не велик.",
		},
		{
			"name": "Семья отца живёт в городе.",
			"id": "latinN_3_GE_s_31221be2",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Familia patris in urbe habitat. — Семья отца живёт в городе.",
			"test": "<…> Familia patris in urbe habitat. — Семья отца живёт в городе.",
		},
		{
			"name": "Носы кораблей прекрасны.",
			"id": "latinN_3_GE_s_377dca04",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Capita navis pulchra sunt. — Носы кораблей прекрасны.",
			"test": "<…> Capita navis pulchra sunt. — Носы кораблей прекрасны.",
		},
		{
			"name": "Народ города счастлив.",
			"id": "latinN_3_GE_s_728938a9",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Populus urbis laetus est. — Народ города счастлив.",
			"test": "<…> Populus urbis laetus est. — Народ города счастлив.",
		},
		{
			"name": "Тайна ночи глубокая.",
			"id": "latinN_3_GE_s_21b8d17c",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Mysterium noctis profundum est. — Тайна ночи глубокая.",
			"test": "<…> Mysterium noctis profundum est. — Тайна ночи глубокая.",
		},
		{
			"name": "Знак имени ясный.",
			"id": "latinN_3_GE_s_6433a2",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Signum nominis clarum est. — Знак имени ясный.",
			"test": "<…> Signum nominis clarum est. — Знак имени ясный.",
		},
		{
			"name": "Слава льва известна.",
			"id": "latinN_3_GE_s_5910e440",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Gloria leonis nota est. — Слава льва известна.",
			"test": "<…> Gloria leonis nota est. — Слава льва известна.",
		},
		{
			"name": "Слова отца полны мудрости.",
			"id": "latinN_3_GE_s_6267c3bb",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Verba patris sapientia plena sunt. — Слова отца полны мудрости.",
			"test": "<…> Verba patris sapientia plena sunt. — Слова отца полны мудрости.",
		},
		{
			"name": "Добыча передаётся льву.",
			"id": "latinN_3_DA_s_533ddba",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Praeda leoni traditur. — Добыча передаётся льву.",
			"test": "<…> Praeda leoni traditur. — Добыча передаётся льву.",
		},
		{
			"name": "Я даю совет отцу.",
			"id": "latinN_3_DA_s_246b179d",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Consilium patri do. — Я даю совет отцу.",
			"test": "<…> Consilium patri do. — Я даю совет отцу.",
		},
		{
			"name": "Порт подготовлен для корабля.",
			"id": "latinN_3_DA_s_7a07c5b4",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Portus navi paratus est. — Порт подготовлен для корабля.",
			"test": "<…> Portus navi paratus est. — Порт подготовлен для корабля.",
		},
		{
			"name": "Помощь городу необходима.",
			"id": "latinN_3_DA_s_26a1ab54",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Auxilium urbī opus est. — Помощь городу необходима.",
			"test": "<…> Auxilium urbī opus est. — Помощь городу необходима.",
		},
		{
			"name": "Мы радуемся покою ночи.",
			"id": "latinN_3_DA_s_3d646c37",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Quieti nocti gaudemus. — Мы радуемся покою ночи.",
			"test": "<…> Quieti nocti gaudemus. — Мы радуемся покою ночи.",
		},
		{
			"name": "Значение добавляется имени.",
			"id": "latinN_3_DA_s_41cf53f9",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Significatio nomini additur. — Значение добавляется имени.",
			"test": "<…> Significatio nomini additur. — Значение добавляется имени.",
		},
		{
			"name": "Я посылаю дар льву.",
			"id": "latinN_3_DA_s_5a10411",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Donum leoni mitto. — Я посылаю дар льву.",
			"test": "<…> Donum leoni mitto. — Я посылаю дар льву.",
		},
		{
			"name": "Слова говорятся отцу.",
			"id": "latinN_3_DA_s_2ef1e4fa",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Verba patri dicuntur. — Слова говорятся отцу.",
			"test": "<…> Verba patri dicuntur. — Слова говорятся отцу.",
		},
		{
			"name": "Благополучие корабля наилучшее.",
			"id": "latinN_3_DA_s_306a30c7",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Salus navi optima est. — Благополучие корабля наилучшее.",
			"test": "<…> Salus navi optima est. — Благополучие корабля наилучшее.",
		},
		{
			"name": "Мы желаем мира городу.",
			"id": "latinN_3_DA_s_b81eda8",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Pacem urbī optamus. — Мы желаем мира городу.",
			"test": "<…> Pacem urbī optamus. — Мы желаем мира городу.",
		},
		{
			"name": "Время подходит для ночи.",
			"id": "latinN_3_DA_s_68de145",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Tempus nocti adest. — Время подходит для ночи.",
			"test": "<…> Tempus nocti adest. — Время подходит для ночи.",
		},
		{
			"name": "Почесть причитается имени.",
			"id": "latinN_3_DA_s_27fa135a",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Honor nomini debetur. — Почесть причитается имени.",
			"test": "<…> Honor nomini debetur. — Почесть причитается имени.",
		},
		{
			"name": "Помощь льву не нужна.",
			"id": "latinN_3_DA_s_46f7f36a",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Auxilium leoni non opus est. — Помощь льву не нужна.",
			"test": "<…> Auxilium leoni non opus est. — Помощь льву не нужна.",
		},
		{
			"name": "Книга передаётся отцу.",
			"id": "latinN_3_DA_s_421faab1",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Liber patri traditur. — Книга передаётся отцу.",
			"test": "<…> Liber patri traditur. — Книга передаётся отцу.",
		},
		{
			"name": "Мир наилучший для корабля.",
			"id": "latinN_3_DA_s_2b71fc7e",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Pax navi optima est. — Мир наилучший для корабля.",
			"test": "<…> Pax navi optima est. — Мир наилучший для корабля.",
		},
		{
			"name": "Обет возносится городу.",
			"id": "latinN_3_DA_s_5ce65a89",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Votum urbī agitur. — Обет возносится городу.",
			"test": "<…> Votum urbī agitur. — Обет возносится городу.",
		},
		{
			"name": "Я вижу льва в лесу.",
			"id": "latinN_3_AC_s_25f38edc",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Leonem in silva video. — Я вижу льва в лесу.",
			"test": "<…> Leonem in silva video. — Я вижу льва в лесу.",
		},
		{
			"name": "Я приветствую отца в поле.",
			"id": "latinN_3_AC_s_1a86f2f1",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Patrem in agro saluto. — Я приветствую отца в поле.",
			"test": "<…> Patrem in agro saluto. — Я приветствую отца в поле.",
		},
		{
			"name": "Я рассматриваю корабль в море.",
			"id": "latinN_3_AC_s_3eb07fd3",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Navem in mari specto. — Я рассматриваю корабль в море.",
			"test": "<…> Navem in mari specto. — Я рассматриваю корабль в море.",
		},
		{
			"name": "Мы любим большой город.",
			"id": "latinN_3_AC_s_506c589e",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Urbem magnam amamus. — Мы любим большой город.",
			"test": "<…> Urbem magnam amamus. — Мы любим большой город.",
		},
		{
			"name": "Мы боимся тёмной ночи.",
			"id": "latinN_3_AC_s_69d0a921",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Noctem obscuram timemus. — Мы боимся тёмной ночи.",
			"test": "<…> Noctem obscuram timemus. — Мы боимся тёмной ночи.",
		},
		{
			"name": "Мы учим новое имя.",
			"id": "latinN_3_AC_s_446cdf90",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Nomen novum discimus. — Мы учим новое имя.",
			"test": "<…> Nomen novum discimus. — Мы учим новое имя.",
		},
		{
			"name": "Мы хвалим сильного льва.",
			"id": "latinN_3_AC_s_799f7e29",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Leonem fortem laudamus. — Мы хвалим сильного льва.",
			"test": "<…> Leonem fortem laudamus. — Мы хвалим сильного льва.",
		},
		{
			"name": "Мы приветствуем отца с почётом.",
			"id": "latinN_3_AC_s_4b85612c",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Patrem cum honore salutamus. — Мы приветствуем отца с почётом.",
			"test": "<…> Patrem cum honore salutamus. — Мы приветствуем отца с почётом.",
		},
		{
			"name": "Мы видели прекрасный корабль в порту.",
			"id": "latinN_3_AC_s_277050dc",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Navem pulchram in portu vidimus. — Мы видели прекрасный корабль в порту.",
			"test": "<…> Navem pulchram in portu vidimus. — Мы видели прекрасный корабль в порту.",
		},
		{
			"name": "Мы посещаем древний город.",
			"id": "latinN_3_AC_s_5c29bfd",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Urbem antiquam visitamus. — Мы посещаем древний город.",
			"test": "<…> Urbem antiquam visitamus. — Мы посещаем древний город.",
		},
		{
			"name": "Мы желаем спокойной ночи.",
			"id": "latinN_3_AC_s_7aec35a",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Noctem tranquillam optamus. — Мы желаем спокойной ночи.",
			"test": "<…> Noctem tranquillam optamus. — Мы желаем спокойной ночи.",
		},
		{
			"name": "Мы слышали славное имя.",
			"id": "latinN_3_AC_s_67424e82",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Nomen clarum audivimus. — Мы слышали славное имя.",
			"test": "<…> Nomen clarum audivimus. — Мы слышали славное имя.",
		},
		{
			"name": "Он приказывает льву бежать.",
			"id": "latinN_3_AC_s_42110406",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Leonem currere iubet. — Он приказывает льву бежать.",
			"test": "<…> Leonem currere iubet. — Он приказывает льву бежать.",
		},
		{
			"name": "Я вижу работающего отца.",
			"id": "latinN_3_AC_s_531d72ca",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Patrem laborantem video. — Я вижу работающего отца.",
			"test": "<…> Patrem laborantem video. — Я вижу работающего отца.",
		},
		{
			"name": "Мы ведём корабль к порту.",
			"id": "latinN_3_AC_s_22d8cfe0",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Navem ad portum ducimus. — Мы ведём корабль к порту.",
			"test": "<…> Navem ad portum ducimus. — Мы ведём корабль к порту.",
		},
		{
			"name": "Мы спасаем город от опасности.",
			"id": "latinN_3_AC_s_579bb367",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Urbem a periculo servamus. — Мы спасаем город от опасности.",
			"test": "<…> Urbem a periculo servamus. — Мы спасаем город от опасности.",
		},
		{
			"name": "Увидев открыто льва, мы убегаем.",
			"id": "latinN_3_AB_s_1de0aca6",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Leone aperte spectato, fugimus. — Увидев открыто льва, мы убегаем.",
			"test": "<…> Leone aperte spectato, fugimus. — Увидев открыто льва, мы убегаем.",
		},
		{
			"name": "Я был похвален отцом.",
			"id": "latinN_3_AB_s_255316f2",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "A patre laudatus sum. — Я был похвален отцом.",
			"test": "<…> A patre laudatus sum. — Я был похвален отцом.",
		},
		{
			"name": "Мы радуемся кораблю, устойчиво стоящему в порту.",
			"id": "latinN_3_AB_s_41906a77",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Navi in portu stabili gaudemus. — Мы радуемся кораблю, устойчиво стоящему в порту.",
			"test": "<…> Navi in portu stabili gaudemus. — Мы радуемся кораблю, устойчиво стоящему в порту.",
		},
		{
			"name": "Мы уходим из города.",
			"id": "latinN_3_AB_s_4b9af9a9",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Ab urbe discedimus. — Мы уходим из города.",
			"test": "<…> Ab urbe discedimus. — Мы уходим из города.",
		},
		{
			"name": "Мы боимся тёмной ночью.",
			"id": "latinN_3_AB_s_5387f9e0",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Nocte obscura timemur. — Мы боимся тёмной ночью.",
			"test": "<…> Nocte obscura timemur. — Мы боимся тёмной ночью.",
		},
		{
			"name": "Он известен под славным именем.",
			"id": "latinN_3_AB_s_6e5e91e4",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Nomine claro cognitus est. — Он известен под славным именем.",
			"test": "<…> Nomine claro cognitus est. — Он известен под славным именем.",
		},
		{
			"name": "Когда лев возбуждён гневом, я боюсь.",
			"id": "latinN_3_AB_s_2cdf8d8a",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Leone cum ira agitato, timeo. — Когда лев возбуждён гневом, я боюсь.",
			"test": "<…> Leone cum ira agitato, timeo. — Когда лев возбуждён гневом, я боюсь.",
		},
		{
			"name": "Я гуляю с отцом в саду.",
			"id": "latinN_3_AB_s_30946e09",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Cum patre in horto ambulo. — Я гуляю с отцом в саду.",
			"test": "<…> Cum patre in horto ambulo. — Я гуляю с отцом в саду.",
		},
		{
			"name": "Мы радуемся кораблю с полными парусами.",
			"id": "latinN_3_AB_s_5cb0d902",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Navi cum velis plenis gaudemus. — Мы радуемся кораблю с полными парусами.",
			"test": "<…> Navi cum velis plenis gaudemus. — Мы радуемся кораблю с полными парусами.",
		},
		{
			"name": "Мы возвращаемся из большого города.",
			"id": "latinN_3_AB_s_46fbb2c1",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "E urbe magna revenimus. — Мы возвращаемся из большого города.",
			"test": "<…> E urbe magna revenimus. — Мы возвращаемся из большого города.",
		},
		{
			"name": "Мы спим спокойной ночью.",
			"id": "latinN_3_AB_s_1698c449",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Nocte tranquilla dormimus. — Мы спим спокойной ночью.",
			"test": "<…> Nocte tranquilla dormimus. — Мы спим спокойной ночью.",
		},
		{
			"name": "Он называется новым именем.",
			"id": "latinN_3_AB_s_5ef04b5",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Nomine novo appellatur. — Он называется новым именем.",
			"test": "<…> Nomine novo appellatur. — Он называется новым именем.",
		},
		{
			"name": "Когда лев идёт из леса, я боюсь.",
			"id": "latinN_3_AB_s_5f4da5c3",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Leone ab silva veniente, timeo. — Когда лев идёт из леса, я боюсь.",
			"test": "<…> Leone ab silva veniente, timeo. — Когда лев идёт из леса, я боюсь.",
		},
		{
			"name": "Я был любим отцом с любовью.",
			"id": "latinN_3_AB_s_443b7951",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "A patre cum amore amatus sum. — Я был любим отцом с любовью.",
			"test": "<…> A patre cum amore amatus sum. — Я был любим отцом с любовью.",
		},
		{
			"name": "Мы радуемся кораблю, стоящему у берега.",
			"id": "latinN_3_AB_s_14514713",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Navi prope litus stabili gaudemus. — Мы радуемся кораблю, стоящему у берега.",
			"test": "<…> Navi prope litus stabili gaudemus. — Мы радуемся кораблю, стоящему у берега.",
		},
		{
			"name": "Мы уходим в подходящее время.",
			"id": "latinN_3_AB_s_69663380",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Tempore opportuno discedimus. — Мы уходим в подходящее время.",
			"test": "<…> Tempore opportuno discedimus. — Мы уходим в подходящее время.",
		},
		{
			"name": "Он радуется сильному телу.",
			"id": "latinN_3_AB_s_5b37e0d2",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Corpore valido gaudet. — Он радуется сильному телу.",
			"test": "<…> Corpore valido gaudet. — Он радуется сильному телу.",
		},
		{
			"name": "Человек восхваляется друзьями.",
			"id": "latinN_3_AB_s_4459eb14",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Homo ab amicis laudatur. — Человек восхваляется друзьями.",
			"test": "<…> Homo ab amicis laudatur. — Человек восхваляется друзьями.",
		},
		// plural	
		{
			"name": "Львы обитают в лесах.",
			"id": "latinN_3_NO_p_49c2faae",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Leones in silvis habitant. — Львы обитают в лесах.",
			"test": "<…> Leones in silvis habitant. — Львы обитают в лесах.",
		},
		{
			"name": "Отцы работают в садах.",
			"id": "latinN_3_NO_p_20ad9418",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Patres in hortis laborant. — Отцы работают в садах.",
			"test": "<…> Patres in hortis laborant. — Отцы работают в садах.",
		},
		{
			"name": "Корабли стоят в портах.",
			"id": "latinN_3_NO_p_31cefde0",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Naves in portibus stant. — Корабли стоят в портах.",
			"test": "<…> Naves in portibus stant. — Корабли стоят в портах.",
		},
		{
			"name": "Города велики.",
			"id": "latinN_3_NO_p_439f5b3d",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Urbes magnae sunt. — Города велики.",
			"test": "<…> Urbes magnae sunt. — Города велики.",
		},
		{
			"name": "Ночи тёмные.",
			"id": "latinN_3_NO_p_1d56ce6a",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Noctes obscurae sunt. — Ночи тёмные.",
			"test": "<…> Noctes obscurae sunt. — Ночи тёмные.",
		},
		{
			"name": "Имена мне известны.",
			"id": "latinN_3_NO_p_5197848c",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Nomina mihi nota sunt. — Имена мне известны.",
			"test": "<…> Nomina mihi nota sunt. — Имена мне известны.",
		},
		{
			"name": "Крови львов красные.",
			"id": "latinN_3_GE_p_17f052a3",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Cruores leonum rubentes sunt. — Крови львов красные.",
			"test": "<…> Cruores leonum rubentes sunt. — Крови львов красные.",
		},
		{
			"name": "Любви отцов велики.",
			"id": "latinN_3_GE_p_2e0fa5d3",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Amores patrum magnī sunt. — Любви отцов велики.",
			"test": "<…> Amores patrum magnī sunt. — Любви отцов велики.",
		},
		{
			"name": "Части кораблей сломаны.",
			"id": "latinN_3_GE_p_5010be6",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Partes navium fractae sunt. — Части кораблей сломаны.",
			"test": "<…> Partes navium fractae sunt. — Части кораблей сломаны.",
		},
		{
			"name": "Стены городов высокие.",
			"id": "latinN_3_GE_p_685f4c2e",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Muri urbium alti sunt. — Стены городов высокие.",
			"test": "<…> Muri urbium alti sunt. — Стены городов высокие.",
		},
		{
			"name": "Тишины ночей страшные.",
			"id": "latinN_3_GE_p_7daf6ecc",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Silentia noctium terribilia sunt. — Тишины ночей страшные.",
			"test": "<…> Silentia noctium terribilia sunt. — Тишины ночей страшные.",
		},
		{
			"name": "Начала имён длинные.",
			"id": "latinN_3_GE_p_2e5d6d97",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Initia nominum longa sunt. — Начала имён длинные.",
			"test": "<…> Initia nominum longa sunt. — Начала имён длинные.",
		},
		{
			"name": "Страхи львов не велики.",
			"id": "latinN_3_GE_p_238e0d81",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Timores leonum magnī non sunt. — Страхи львов не велики.",
			"test": "<…> Timores leonum magnī non sunt. — Страхи львов не велики.",
		},
		{
			"name": "Семьи отцов живут в городах.",
			"id": "latinN_3_GE_p_31221be2",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Familiae patrum in urbibus habitant. — Семьи отцов живут в городах.",
			"test": "<…> Familiae patrum in urbibus habitant. — Семьи отцов живут в городах.",
		},
		{
			"name": "Носы кораблей прекрасны.",
			"id": "latinN_3_GE_p_377dca04",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Capita navium pulchra sunt. — Носы кораблей прекрасны.",
			"test": "<…> Capita navium pulchra sunt. — Носы кораблей прекрасны.",
		},
		{
			"name": "Народы городов счастливы.",
			"id": "latinN_3_GE_p_728938a9",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Populi urbium laeti sunt. — Народы городов счастливы.",
			"test": "<…> Populi urbium laeti sunt. — Народы городов счастливы.",
		},
		{
			"name": "Тайны ночей глубокие.",
			"id": "latinN_3_GE_p_21b8d17c",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Mysteria noctium profunda sunt. — Тайны ночей глубокие.",
			"test": "<…> Mysteria noctium profunda sunt. — Тайны ночей глубокие.",
		},
		{
			"name": "Знаки имён ясные.",
			"id": "latinN_3_GE_p_6433a2",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Signa nominum clara sunt. — Знаки имён ясные.",
			"test": "<…> Signa nominum clara sunt. — Знаки имён ясные.",
		},
		{
			"name": "Славы львов известны.",
			"id": "latinN_3_GE_p_5910e440",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Gloriae leonum notae sunt. — Славы львов известны.",
			"test": "<…> Gloriae leonum notae sunt. — Славы львов известны.",
		},
		{
			"name": "Слова отцов полны мудрости.",
			"id": "latinN_3_GE_p_6267c3bb",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Verba patrum sapientia plena sunt. — Слова отцов полны мудрости.",
			"test": "<…> Verba patrum sapientia plena sunt. — Слова отцов полны мудрости.",
		},
		{
			"name": "Добычи передаются львам.",
			"id": "latinN_3_DA_p_533ddba",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Praedae leonibus traduntur. — Добычи передаются львам.",
			"test": "<…> Praedae leonibus traduntur. — Добычи передаются львам.",
		},
		{
			"name": "Я даю советы отцам.",
			"id": "latinN_3_DA_p_246b179d",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Consilia patribus do. — Я даю советы отцам.",
			"test": "<…> Consilia patribus do. — Я даю советы отцам.",
		},
		{
			"name": "Порты подготовлены для кораблей.",
			"id": "latinN_3_DA_p_7a07c5b4",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Portus navibus parati sunt. — Порты подготовлены для кораблей.",
			"test": "<…> Portus navibus parati sunt. — Порты подготовлены для кораблей.",
		},
		{
			"name": "Помощи необходимы городам.",
			"id": "latinN_3_DA_p_26a1ab54",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Auxilia urbibus opus sunt. — Помощи необходимы городам.",
			"test": "<…> Auxilia urbibus opus sunt. — Помощи необходимы городам.",
		},
		{
			"name": "Мы радуемся покою ночей.",
			"id": "latinN_3_DA_p_3d646c37",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Quieti noctibus gaudemus. — Мы радуемся покою ночей.",
			"test": "<…> Quieti noctibus gaudemus. — Мы радуемся покою ночей.",
		},
		{
			"name": "Значения добавляются именам.",
			"id": "latinN_3_DA_p_41cf53f9",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Significationes nominibus adduntur. — Значения добавляются именам.",
			"test": "<…> Significationes nominibus adduntur. — Значения добавляются именам.",
		},
		{
			"name": "Я посылаю дары львам.",
			"id": "latinN_3_DA_p_5a10411",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Dona leonibus mitto. — Я посылаю дары львам.",
			"test": "<…> Dona leonibus mitto. — Я посылаю дары львам.",
		},
		{
			"name": "Слова говорятся старейшинам (отцам).",
			"id": "latinN_3_DA_p_2ef1e4fa",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Verba patriarchis dicuntur. — Слова говорятся старейшинам (отцам).",
			"test": "<…> Verba patriarchis dicuntur. — Слова говорятся старейшинам (отцам).",
		},
		{
			"name": "Благополучие кораблей наилучшее.",
			"id": "latinN_3_DA_p_306a30c7",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Salus navibus optima est. — Благополучие кораблей наилучшее.",
			"test": "<…> Salus navibus optima est. — Благополучие кораблей наилучшее.",
		},
		{
			"name": "Мы желаем мира городам.",
			"id": "latinN_3_DA_p_b81eda8",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Pacem urbibus optamus. — Мы желаем мира городам.",
			"test": "<…> Pacem urbibus optamus. — Мы желаем мира городам.",
		},
		{
			"name": "Времена подходят для ночей.",
			"id": "latinN_3_DA_p_68de145",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Tempora noctibus adest. — Времена подходят для ночей.",
			"test": "<…> Tempora noctibus adest. — Времена подходят для ночей.",
		},
		{
			"name": "Почести причитаются именам.",
			"id": "latinN_3_DA_p_27fa135a",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Honores nominibus debentur. — Почести причитаются именам.",
			"test": "<…> Honores nominibus debentur. — Почести причитаются именам.",
		},
		{
			"name": "Помощи львам не нужны.",
			"id": "latinN_3_DA_p_46f7f36a",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Auxilia leonibus non opus sunt. — Помощи львам не нужны.",
			"test": "<…> Auxilia leonibus non opus sunt. — Помощи львам не нужны.",
		},
		{
			"name": "Книги передаются отцам.",
			"id": "latinN_3_DA_p_421faab1",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Libri patribus traduntur. — Книги передаются отцам.",
			"test": "<…> Libri patribus traduntur. — Книги передаются отцам.",
		},
		{
			"name": "Мир наилучший для кораблей.",
			"id": "latinN_3_DA_p_2b71fc7e",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Pax navibus optima est. — Мир наилучший для кораблей.",
			"test": "<…> Pax navibus optima est. — Мир наилучший для кораблей.",
		},
		{
			"name": "Обеты возносятся городам.",
			"id": "latinN_3_DA_p_5ce65a89",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Vota urbibus aguntur. — Обеты возносятся городам.",
			"test": "<…> Vota urbibus aguntur. — Обеты возносятся городам.",
		},
		{
			"name": "Я вижу львов в лесах.",
			"id": "latinN_3_AC_p_25f38edc",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Leones in silvis video. — Я вижу львов в лесах.",
			"test": "<…> Leones in silvis video. — Я вижу львов в лесах.",
		},
		{
			"name": "Я приветствую отцов в полях.",
			"id": "latinN_3_AC_p_1a86f2f1",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Patres in agris saluto. — Я приветствую отцов в полях.",
			"test": "<…> Patres in agris saluto. — Я приветствую отцов в полях.",
		},
		{
			"name": "Я рассматриваю корабли в море.",
			"id": "latinN_3_AC_p_3eb07fd3",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Naves in mari specto. — Я рассматриваю корабли в море.",
			"test": "<…> Naves in mari specto. — Я рассматриваю корабли в море.",
		},
		{
			"name": "Мы любим большие города.",
			"id": "latinN_3_AC_p_506c589e",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Urbes magnas amamus. — Мы любим большие города.",
			"test": "<…> Urbes magnas amamus. — Мы любим большие города.",
		},
		{
			"name": "Мы боимся тёмных ночей.",
			"id": "latinN_3_AC_p_69d0a921",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Noctes obscuras timemus. — Мы боимся тёмных ночей.",
			"test": "<…> Noctes obscuras timemus. — Мы боимся тёмных ночей.",
		},
		{
			"name": "Мы учим новые имена.",
			"id": "latinN_3_AC_p_446cdf90",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Nomina nova discimus. — Мы учим новые имена.",
			"test": "<…> Nomina nova discimus. — Мы учим новые имена.",
		},
		{
			"name": "Мы хвалим сильных львов.",
			"id": "latinN_3_AC_p_799f7e29",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Leones fortes laudamus. — Мы хвалим сильных львов.",
			"test": "<…> Leones fortes laudamus. — Мы хвалим сильных львов.",
		},
		{
			"name": "Мы приветствуем отцов с почётом.",
			"id": "latinN_3_AC_p_4b85612c",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Patres cum honore salutamus. — Мы приветствуем отцов с почётом.",
			"test": "<…> Patres cum honore salutamus. — Мы приветствуем отцов с почётом.",
		},
		{
			"name": "Мы видели прекрасные корабли в портах.",
			"id": "latinN_3_AC_p_277050dc",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Naves pulchras in portibus vidimus. — Мы видели прекрасные корабли в портах.",
			"test": "<…> Naves pulchras in portibus vidimus. — Мы видели прекрасные корабли в портах.",
		},
		{
			"name": "Мы посещаем древние города.",
			"id": "latinN_3_AC_p_5c29bfd",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Urbes antiquas visitamus. — Мы посещаем древние города.",
			"test": "<…> Urbes antiquas visitamus. — Мы посещаем древние города.",
		},
		{
			"name": "Мы желаем спокойных ночей.",
			"id": "latinN_3_AC_p_7aec35a",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Noctes tranquillas optamus. — Мы желаем спокойных ночей.",
			"test": "<…> Noctes tranquillas optamus. — Мы желаем спокойных ночей.",
		},
		{
			"name": "Мы слышали славные имена.",
			"id": "latinN_3_AC_p_67424e82",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Nomina clara audivimus. — Мы слышали славные имена.",
			"test": "<…> Nomina clara audivimus. — Мы слышали славные имена.",
		},
		{
			"name": "Мы приказываем львам бежать.",
			"id": "latinN_3_AC_p_42110406",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Leones currere iubemus. — Мы приказываем львам бежать.",
			"test": "<…> Leones currere iubemus. — Мы приказываем львам бежать.",
		},
		{
			"name": "Я вижу работающих отцов.",
			"id": "latinN_3_AC_p_531d72ca",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Patres laborantes video. — Я вижу работающих отцов.",
			"test": "<…> Patres laborantes video. — Я вижу работающих отцов.",
		},
		{
			"name": "Мы ведём корабли к портам.",
			"id": "latinN_3_AC_p_22d8cfe0",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Naves ad portus ducimus. — Мы ведём корабли к портам.",
			"test": "<…> Naves ad portus ducimus. — Мы ведём корабли к портам.",
		},
		{
			"name": "Мы спасаем города от опасности.",
			"id": "latinN_3_AC_p_579bb367",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Urbes a periculo servamus. — Мы спасаем города от опасности.",
			"test": "<…> Urbes a periculo servamus. — Мы спасаем города от опасности.",
		},
		{
			"name": "Увидев открыто львов, мы убегаем.",
			"id": "latinN_3_AB_p_1de0aca6",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Leonibus aperte spectatis, fugimus. — Увидев открыто львов, мы убегаем.",
			"test": "<…> Leonibus aperte spectatis, fugimus. — Увидев открыто львов, мы убегаем.",
		},
		{
			"name": "Мы были похвалены отцами.",
			"id": "latinN_3_AB_p_255316f2",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "A patribus laudati sumus. — Мы были похвалены отцами.",
			"test": "<…> A patribus laudati sumus. — Мы были похвалены отцами.",
		},
		{
			"name": "Мы радуемся кораблям, устойчиво стоящим в портах.",
			"id": "latinN_3_AB_p_41906a77",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Navibus in portibus stabilibus gaudemus. — Мы радуемся кораблям, устойчиво стоящим в портах.",
			"test": "<…> Navibus in portibus stabilibus gaudemus. — Мы радуемся кораблям, устойчиво стоящим в портах.",
		},
		{
			"name": "Мы уходим из городов.",
			"id": "latinN_3_AB_p_4b9af9a9",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Ab urbibus discedimus. — Мы уходим из городов.",
			"test": "<…> Ab urbibus discedimus. — Мы уходим из городов.",
		},
		{
			"name": "Мы боялись тёмными ночами.",
			"id": "latinN_3_AB_p_5387f9e0",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Noctibus obscuris timebamus. — Мы боялись тёмными ночами.",
			"test": "<…> Noctibus obscuris timebamus. — Мы боялись тёмными ночами.",
		},
		{
			"name": "Мы известны под славными именами.",
			"id": "latinN_3_AB_p_6e5e91e4",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Nominibus claris cogniti sumus. — Мы известны под славными именами.",
			"test": "<…> Nominibus claris cogniti sumus. — Мы известны под славными именами.",
		},
		{
			"name": "Когда львы возбуждены гневом, я боюсь.",
			"id": "latinN_3_AB_p_2cdf8d8a",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Leonibus cum ira agitatis, timeo. — Когда львы возбуждены гневом, я боюсь.",
			"test": "<…> Leonibus cum ira agitatis, timeo. — Когда львы возбуждены гневом, я боюсь.",
		},
		{
			"name": "Мы гуляем с отцами в садах.",
			"id": "latinN_3_AB_p_30946e09",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Cum patribus in hortis ambulamus. — Мы гуляем с отцами в садах.",
			"test": "<…> Cum patribus in hortis ambulamus. — Мы гуляем с отцами в садах.",
		},
		{
			"name": "Мы радуемся кораблям с полными парусами.",
			"id": "latinN_3_AB_p_5cb0d902",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Navibus cum velis plenis gaudemus. — Мы радуемся кораблям с полными парусами.",
			"test": "<…> Navibus cum velis plenis gaudemus. — Мы радуемся кораблям с полными парусами.",
		},
		{
			"name": "Мы возвращаемся из больших городов.",
			"id": "latinN_3_AB_p_46fbb2c1",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "E urbibus magnis revenimus. — Мы возвращаемся из больших городов.",
			"test": "<…> E urbibus magnis revenimus. — Мы возвращаемся из больших городов.",
		},
		{
			"name": "Мы спим спокойными ночами.",
			"id": "latinN_3_AB_p_1698c449",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Noctibus tranquillis dormimus. — Мы спим спокойными ночами.",
			"test": "<…> Noctibus tranquillis dormimus. — Мы спим спокойными ночами.",
		},
		{
			"name": "Нас называют новыми именами.",
			"id": "latinN_3_AB_p_5ef04b5",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Nominibus novis appellamur. — Нас называют новыми именами.",
			"test": "<…> Nominibus novis appellamur. — Нас называют новыми именами.",
		},
		{
			"name": "Когда львы идут из лесов, мы боимся.",
			"id": "latinN_3_AB_p_5f4da5c3",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Leonibus ab silvis venientibus, timemus. — Когда львы идут из лесов, мы боимся.",
			"test": "<…> Leonibus ab silvis venientibus, timemus. — Когда львы идут из лесов, мы боимся.",
		},
		{
			"name": "Мы были любимы отцами с любовью.",
			"id": "latinN_3_AB_p_443b7951",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "A patribus cum amore amati sumus. — Мы были любимы отцами с любовью.",
			"test": "<…> A patribus cum amore amati sumus. — Мы были любимы отцами с любовью.",
		},
		{
			"name": "Мы радуемся кораблям, стоящим у берегов.",
			"id": "latinN_3_AB_p_14514713",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Navibus prope litora stabilibus gaudemus. — Мы радуемся кораблям, стоящим у берегов.",
			"test": "<…> Navibus prope litora stabilibus gaudemus. — Мы радуемся кораблям, стоящим у берегов.",
		},
		{
			"name": "Мы уходим в подходящие времена.",
			"id": "latinN_3_AB_p_69663380",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Temporibus opportunis discedimus. — Мы уходим в подходящие времена.",
			"test": "<…> Temporibus opportunis discedimus. — Мы уходим в подходящие времена.",
		},
		{
			"name": "Они радуются сильным телам.",
			"id": "latinN_3_AB_p_5b37e0d2",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Corporibus validis gaudent. — Они радуются сильным телам.",
			"test": "<…> Corporibus validis gaudent. — Они радуются сильным телам.",
		},
		{
			"name": "Люди восхваляются друзьями.",
			"id": "latinN_3_AB_p_4459eb14",
			"grade": "latin_noun",
			"letters": ["3"],
			"full": "Homines ab amicis laudantur. — Люди восхваляются друзьями.",
			"test": "<…> Homines ab amicis laudantur. — Люди восхваляются друзьями.",
		}
	);
}
