/*
* Copyright (c) AParovyshnaya 2020-2026
* 
* AParovyshnaya and theirs affiliates make no warranty of any kind
* with regard to this material. 
* 
* AParovyshnaya expressly disclaims all warranties as to the material, express, 
* and implied, including but not limited to the implied warranties of 
* merchantability, fitness for a particular purpose and non-infringement of third 
* party rights. 
* 
* In no event shall AParovyshnaya be liable to you or any other person for any damages, 
* including, without limitation, any direct, indirect, incidental or consequential 
* damages, expenses, lost profits, lost data or other damages arising out of the use, 
* misuse or inability to use the material and any derived software, even if AParovyshnaya, 
* their affiliate or an authorized dealer has been advised of the possibility of such damages. 
* 
*/

export function withLatinNoun4Tests() {
	data.data.push(
		// singular
		{
			"name": "Плод висит на дереве.",
			"id": "latinN_4_NO_s_442675e1",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fructus in arbore pendet. — Плод висит на дереве.",
			"test": "<…> Fructus in arbore pendet. — Плод висит на дереве.",
		},
		{
			"name": "Дух свят.",
			"id": "latinN_4_NO_s_6166e06f",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Spiritus sanctus est. — Дух свят.",
			"test": "<…> Spiritus sanctus est. — Дух свят.",
		},
		{
			"name": "Рука прекрасна.",
			"id": "latinN_4_NO_s_49e202ad",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Manus pulchra est. — Рука прекрасна.",
			"test": "<…> Manus pulchra est. — Рука прекрасна.",
		},
		{
			"name": "Колено сломано.",
			"id": "latinN_4_NO_s_1c72da34",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Genu fractum est. — Колено сломано.",
			"test": "<…> Genu fractum est. — Колено сломано.",
		},
		{
			"name": "Рог длинный.",
			"id": "latinN_4_NO_s_6b0c2d26",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Cornu longum est. — Рог длинный.",
			"test": "<…> Cornu longum est. — Рог длинный.",
		},
		{
			"name": "Вертел греется в огне.",
			"id": "latinN_4_NO_s_3d3fcdb0",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Veru in igne calet. — Вертел греется в огне.",
			"test": "<…> Veru in igne calet. — Вертел греется в огне.",
		},
		{
			"name": "Вкус плода сладкий.",
			"id": "latinN_4_GE_s_641147d0",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Sapor fructus dulcis est. — Вкус плода сладкий.",
			"test": "<…> Sapor fructus dulcis est. — Вкус плода сладкий.",
		},
		{
			"name": "Природа духа неясна.",
			"id": "latinN_4_GE_s_6e38921c",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Natura spiritus obscura est. — Природа духа неясна.",
			"test": "<…> Natura spiritus obscura est. — Природа духа неясна.",
		},
		{
			"name": "Красота руки восхитительна.",
			"id": "latinN_4_GE_s_64d7f7e0",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Pulchritudo manus admirabilis est. — Красота руки восхитительна.",
			"test": "<…> Pulchritudo manus admirabilis est. — Красота руки восхитительна.",
		},
		{
			"name": "Высота колена мала.",
			"id": "latinN_4_GE_s_27c6e487",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Altitude genu parva est. — Высота колена мала.",
			"test": "<…> Altitude genu parva est. — Высота колена мала.",
		},
		{
			"name": "Длина рога велика.",
			"id": "latinN_4_GE_s_49070868",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Longitudo cornus magna est. — Длина рога велика.",
			"test": "<…> Longitudo cornus magna est. — Длина рога велика.",
		},
		{
			"name": "Использование вертела необходимо.",
			"id": "latinN_4_GE_s_6385cb26",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Usus verū necessarius est. — Использование вертела необходимо.",
			"test": "<…> Usus verū necessarius est. — Использование вертела необходимо.",
		},
		{
			"name": "Цвет плода красный.",
			"id": "latinN_4_GE_s_38364841",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Colore fructus rubrum est. — Цвет плода красный.",
			"test": "<…> Colore fructus rubrum est. — Цвет плода красный.",
		},
		{
			"name": "Память духа долгая.",
			"id": "latinN_4_GE_s_28c4711c",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Memoria spiritus longa est. — Память духа долгая.",
			"test": "<…> Memoria spiritus longa est. — Память духа долгая.",
		},
		{
			"name": "Ловкость руки очень велика.",
			"id": "latinN_4_GE_s_59717824",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Agilitas manus maxima est. — Ловкость руки очень велика.",
			"test": "<…> Agilitas manus maxima est. — Ловкость руки очень велика.",
		},
		{
			"name": "Прочность колена крепкая.",
			"id": "latinN_4_GE_s_146044d7",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Firmitas genu valida est. — Прочность колена крепкая.",
			"test": "<…> Firmitas genu valida est. — Прочность колена крепкая.",
		},
		{
			"name": "Сила рога восхитительна.",
			"id": "latinN_4_GE_s_1e9e725a",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fortitudo cornus admirabilis est. — Сила рога восхитительна.",
			"test": "<…> Fortitudo cornus admirabilis est. — Сила рога восхитительна.",
		},
		{
			"name": "Полезность вертела велика.",
			"id": "latinN_4_GE_s_15d9bc04",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Utilitas verū magna est. — Полезность вертела велика.",
			"test": "<…> Utilitas verū magna est. — Полезность вертела велика.",
		},
		{
			"name": "Запах плода приятен.",
			"id": "latinN_4_GE_s_473b46c3",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Odor fructus suavis est. — Запах плода приятен.",
			"test": "<…> Odor fructus suavis est. — Запах плода приятен.",
		},
		{
			"name": "Мощь духа велика.",
			"id": "latinN_4_GE_s_516be40f",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Potentia spiritus magna est. — Мощь духа велика.",
			"test": "<…> Potentia spiritus magna est. — Мощь духа велика.",
		},
		{
			"name": "Дар плоду мал.",
			"id": "latinN_4_DA_s_3c0a50da",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Donum fructui parvum est. — Дар плоду мал.",
			"test": "<…> Donum fructui parvum est. — Дар плоду мал.",
		},
		{
			"name": "Я даю совет духу.",
			"id": "latinN_4_DA_s_646be2c3",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Consilium spiritui do. — Я даю совет духу.",
			"test": "<…> Consilium spiritui do. — Я даю совет духу.",
		},
		{
			"name": "Помощь руке необходима.",
			"id": "latinN_4_DA_s_797badd3",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Auxilium manui opus est. — Помощь руке необходима.",
			"test": "<…> Auxilium manui opus est. — Помощь руке необходима.",
		},
		{
			"name": "Благополучие колена наилучшее.",
			"id": "latinN_4_DA_s_77be656f",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Salus genu optima est. — Благополучие колена наилучшее.",
			"test": "<…> Salus genu optima est. — Благополучие колена наилучшее.",
		},
		{
			"name": "Почесть причитается рогу.",
			"id": "latinN_4_DA_s_19dc67c2",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Honor cornui debetur. — Почесть причитается рогу.",
			"test": "<…> Honor cornui debetur. — Почесть причитается рогу.",
		},
		{
			"name": "Мы служим использованию вертела.",
			"id": "latinN_4_DA_s_221af3c0",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Usui verui servimus. — Мы служим использованию вертела.",
			"test": "<…> Usui verui servimus. — Мы служим использованию вертела.",
		},
		{
			"name": "Награда обещана плоду.",
			"id": "latinN_4_DA_s_62bd765",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Praemium fructui promittitur. — Награда обещана плоду.",
			"test": "<…> Praemium fructui promittitur. — Награда обещана плоду.",
		},
		{
			"name": "Слова говорятся духу.",
			"id": "latinN_4_DA_s_23a5fd2",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Verba spiritui dicuntur. — Слова говорятся духу.",
			"test": "<…> Verba spiritui dicuntur. — Слова говорятся духу.",
		},
		{
			"name": "Украшение даётся руке.",
			"id": "latinN_4_DA_s_78a2da20",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Ornamentum manui datur. — Украшение даётся руке.",
			"test": "<…> Ornamentum manui datur. — Украшение даётся руке.",
		},
		{
			"name": "Лечение колена необходимо.",
			"id": "latinN_4_DA_s_dd3b207",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Curatio genu necessaria est. — Лечение колена необходимо.",
			"test": "<…> Curatio genu necessaria est. — Лечение колена необходимо.",
		},
		{
			"name": "Хвала возносится рогу.",
			"id": "latinN_4_DA_s_551bdc27",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Laus cornui agitur. — Хвала возносится рогу.",
			"test": "<…> Laus cornui agitur. — Хвала возносится рогу.",
		},
		{
			"name": "Инструмент для вертела приготовлен.",
			"id": "latinN_4_DA_s_58fdd99",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Instrumentum verui paratum est. — Инструмент для вертела приготовлен.",
			"test": "<…> Instrumentum verui paratum est. — Инструмент для вертела приготовлен.",
		},
		{
			"name": "Благодарности возносятся плоду.",
			"id": "latinN_4_DA_s_6b1274d2",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Gratiae fructui aguntur. — Благодарности возносятся плоду.",
			"test": "<…> Gratiae fructui aguntur. — Благодарности возносятся плоду.",
		},
		{
			"name": "Книга передаётся духу.",
			"id": "latinN_4_DA_s_7bc1a03d",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Liber spiritui traditur. — Книга передаётся духу.",
			"test": "<…> Liber spiritui traditur. — Книга передаётся духу.",
		},
		{
			"name": "Здоровье руки наилучшее.",
			"id": "latinN_4_DA_s_70b0b186",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Sanitas manui optima est. — Здоровье руки наилучшее.",
			"test": "<…> Sanitas manui optima est. — Здоровье руки наилучшее.",
		},
		{
			"name": "Лекарство для колена приготовлено.",
			"id": "latinN_4_DA_s_ba8d91c",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Remedium genu paratum est. — Лекарство для колена приготовлено.",
			"test": "<…> Remedium genu paratum est. — Лекарство для колена приготовлено.",
		},
		{
			"name": "Я вижу плод на дереве.",
			"id": "latinN_4_AC_s_7364985f",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fructum in arbore video. — Я вижу плод на дереве.",
			"test": "<…> Fructum in arbore video. — Я вижу плод на дереве.",
		},
		{
			"name": "Я поклоняюсь святому духу.",
			"id": "latinN_4_AC_s_5d20e46",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Spiritum sanctum adoro. — Я поклоняюсь святому духу.",
			"test": "<…> Spiritum sanctum adoro. — Я поклоняюсь святому духу.",
		},
		{
			"name": "Я хвалю прекрасную руку.",
			"id": "latinN_4_AC_s_709ba3fb",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Manum pulchram laudo. — Я хвалю прекрасную руку.",
			"test": "<…> Manum pulchram laudo. — Я хвалю прекрасную руку.",
		},
		{
			"name": "Мы лечим сломанное колено.",
			"id": "latinN_4_AC_s_3d36e4cd",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Genu fractum curamus. — Мы лечим сломанное колено.",
			"test": "<…> Genu fractum curamus. — Мы лечим сломанное колено.",
		},
		{
			"name": "Я удивляюсь длинному рогу.",
			"id": "latinN_4_AC_s_6a472554",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Cornu longo miror. — Я удивляюсь длинному рогу.",
			"test": "<…> Cornu longo miror. — Я удивляюсь длинному рогу.",
		},
		{
			"name": "Мы кладём вертел в огонь.",
			"id": "latinN_4_AC_s_7ff2a664",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Verum in igne ponimus. — Мы кладём вертел в огонь.",
			"test": "<…> Verum in igne ponimus. — Мы кладём вертел в огонь.",
		},
		{
			"name": "Я ем сладкий плод.",
			"id": "latinN_4_AC_s_525b461a",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fructum dulcem edo. — Я ем сладкий плод.",
			"test": "<…> Fructum dulcem edo. — Я ем сладкий плод.",
		},
		{
			"name": "Мы любим добрый дух.",
			"id": "latinN_4_AC_s_58c1c010",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Spiritum bonum amamus. — Мы любим добрый дух.",
			"test": "<…> Spiritum bonum amamus. — Мы любим добрый дух.",
		},
		{
			"name": "Я приветствую работающую руку.",
			"id": "latinN_4_AC_s_b7f23d9",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Manum laborantem saluto. — Я приветствую работающую руку.",
			"test": "<…> Manum laborantem saluto. — Я приветствую работающую руку.",
		},
		{
			"name": "Мы хвалим крепкое колено.",
			"id": "latinN_4_AC_s_61d47554",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Genu validum laudamus. — Мы хвалим крепкое колено.",
			"test": "<…> Genu validum laudamus. — Мы хвалим крепкое колено.",
		},
		{
			"name": "Мы рассматриваем большой рог.",
			"id": "latinN_4_AC_s_69b794e2",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Cornu magnum spectamus. — Мы рассматриваем большой рог.",
			"test": "<…> Cornu magnum spectamus. — Мы рассматриваем большой рог.",
		},
		{
			"name": "Мы получаем новый вертел.",
			"id": "latinN_4_AC_s_3f200884",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Verum novum accipimus. — Мы получаем новый вертел.",
			"test": "<…> Verum novum accipimus. — Мы получаем новый вертел.",
		},
		{
			"name": "Я срываю зрелый плод.",
			"id": "latinN_4_AC_s_4d339552",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fructum maturum carpo. — Я срываю зрелый плод.",
			"test": "<…> Fructum maturum carpo. — Я срываю зрелый плод.",
		},
		{
			"name": "Мы боимся злого духа.",
			"id": "latinN_4_AC_s_f0f2775",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Spiritum malum timemus. — Мы боимся злого духа.",
			"test": "<…> Spiritum malum timemus. — Мы боимся злого духа.",
		},
		{
			"name": "Мы держим правую руку.",
			"id": "latinN_4_AC_s_5a4aa2f2",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Manum dexteram tenemus. — Мы держим правую руку.",
			"test": "<…> Manum dexteram tenemus. — Мы держим правую руку.",
		},
		{
			"name": "Больное колено лечится.",
			"id": "latinN_4_AC_s_6591f517",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Genu dolens curatur. — Больное колено лечится.",
			"test": "<…> Genu dolens curatur. — Больное колено лечится.",
		},
		{
			"name": "Мы радуемся сладкому плоду.",
			"id": "latinN_4_AB_s_345965f2",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fructu dulci gaudemus. — Мы радуемся сладкому плоду.",
			"test": "<…> Fructu dulci gaudemus. — Мы радуемся сладкому плоду.",
		},
		{
			"name": "Мы будем защищены святым духом.",
			"id": "latinN_4_AB_s_429bd883",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "A spiritu sancto protegemur. — Мы будем защищены святым духом.",
			"test": "<…> A spiritu sancto protegemur. — Мы будем защищены святым духом.",
		},
		{
			"name": "Картинка рисуется прекрасной рукой.",
			"id": "latinN_4_AB_s_4d49af10",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Manu pulchra pictura pingitur. — Картинка рисуется прекрасной рукой.",
			"test": "<…> Manu pulchra pictura pingitur. — Картинка рисуется прекрасной рукой.",
		},
		{
			"name": "С сломанным коленом ходить трудно.",
			"id": "latinN_4_AB_s_279ad2e3",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Genu fracto ambulare difficile est. — С сломанным коленом ходить трудно.",
			"test": "<…> Genu fracto ambulare difficile est. — С сломанным коленом ходить трудно.",
		},
		{
			"name": "Бык сражается крепким рогом.",
			"id": "latinN_4_AB_s_58134517",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Cornu valido taurus pugnat. — Бык сражается крепким рогом.",
			"test": "<…> Cornu valido taurus pugnat. — Бык сражается крепким рогом.",
		},
		{
			"name": "Мы осторожны с вертелом в огне.",
			"id": "latinN_4_AB_s_4450d156",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Ab veru in igne cauti sumus. — Мы осторожны с вертелом в огне.",
			"test": "<…> Ab veru in igne cauti sumus. — Мы осторожны с вертелом в огне.",
		},
		{
			"name": "Мы насытились зрелым плодом.",
			"id": "latinN_4_AB_s_4461c7e3",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fructu maturo saturati sumus. — Мы насытились зрелым плодом.",
			"test": "<…> Fructu maturo saturati sumus. — Мы насытились зрелым плодом.",
		},
		{
			"name": "Мы сражаемся с сильным духом.",
			"id": "latinN_4_AB_s_351d0846",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Cum spiritu forti pugnamus. — Мы сражаемся с сильным духом.",
			"test": "<…> Cum spiritu forti pugnamus. — Мы сражаемся с сильным духом.",
		},
		{
			"name": "Мы пишем правой рукой.",
			"id": "latinN_4_AB_s_77e4c80f",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Manu dextera scribimus. — Мы пишем правой рукой.",
			"test": "<…> Manu dextera scribimus. — Мы пишем правой рукой.",
		},
		{
			"name": "Он встал с больного колена.",
			"id": "latinN_4_AB_s_35fc6dc4",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "E genu dolente surrexit. — Он встал с больного колена.",
			"test": "<…> E genu dolente surrexit. — Он встал с больного колена.",
		},
		{
			"name": "Бык пугает острым рогом.",
			"id": "latinN_4_AB_s_7fe8ea47",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Cornu acuto taurus terret. — Бык пугает острым рогом.",
			"test": "<…> Cornu acuto taurus terret. — Бык пугает острым рогом.",
		},
		{
			"name": "Мы осторожны с горячим вертелом.",
			"id": "latinN_4_AB_s_226a82c4",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Veru calido cauti sumus. — Мы осторожны с горячим вертелом.",
			"test": "<…> Veru calido cauti sumus. — Мы осторожны с горячим вертелом.",
		},
		{
			"name": "Мы радуемся новому плоду.",
			"id": "latinN_4_AB_s_731f8236",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fructu novo gaudemus. — Мы радуемся новому плоду.",
			"test": "<…> Fructu novo gaudemus. — Мы радуемся новому плоду.",
		},
		{
			"name": "Мы защищаемся от злого духа.",
			"id": "latinN_4_AB_s_255b53dc",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "A spiritu maligno defendimur. — Мы защищаемся от злого духа.",
			"test": "<…> A spiritu maligno defendimur. — Мы защищаемся от злого духа.",
		},
		{
			"name": "Мы держим левой рукой.",
			"id": "latinN_4_AB_s_1dd92fe2",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Manu sinistra tenemus. — Мы держим левой рукой.",
			"test": "<…> Manu sinistra tenemus. — Мы держим левой рукой.",
		},
		{
			"name": "Мы ходим с помощью крепкого колена.",
			"id": "latinN_4_AB_s_6b53e23f",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Per genu validum ambulamus. — Мы ходим с помощью крепкого колена.",
			"test": "<…> Per genu validum ambulamus. — Мы ходим с помощью крепкого колена.",
		},
		{
			"name": "Бык гордится большим рогом.",
			"id": "latinN_4_AB_s_64d2d351",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Cornu magno taurus gloriatur. — Бык гордится большим рогом.",
			"test": "<…> Cornu magno taurus gloriatur. — Бык гордится большим рогом.",
		},
		{
			"name": "Мы пользуемся новым вертелом.",
			"id": "latinN_4_AB_s_1b68b9a4",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Veru novo utimur. — Мы пользуемся новым вертелом.",
			"test": "<…> Veru novo utimur. — Мы пользуемся новым вертелом.",
		},
		// plural	
		{
			"name": "Плоды на деревьях зрелые.",
			"id": "latinN_4_NO_p_49c2faae",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fructus in arboribus maturi sunt. — Плоды на деревьях зрелые.",
			"test": "<…> Fructus in arboribus maturi sunt. — Плоды на деревьях зрелые.",
		},
		{
			"name": "Святые духи почитаются.",
			"id": "latinN_4_NO_p_20ad9418",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Spiritus sancti adorantur. — Святые духи почитаются.",
			"test": "<…> Spiritus sancti adorantur. — Святые духи почитаются.",
		},
		{
			"name": "Прекрасные руки работают.",
			"id": "latinN_4_NO_p_31cefde0",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Manus pulchrae laborant. — Прекрасные руки работают.",
			"test": "<…> Manus pulchrae laborant. — Прекрасные руки работают.",
		},
		{
			"name": "Колени согнуты.",
			"id": "latinN_4_NO_p_439f5b3d",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Genua flexa sunt. — Колени согнуты.",
			"test": "<…> Genua flexa sunt. — Колени согнуты.",
		},
		{
			"name": "Мы рассматриваем длинные рога.",
			"id": "latinN_4_NO_p_1d56ce6a",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Cornua longa spectamus. — Мы рассматриваем длинные рога.",
			"test": "<…> Cornua longa spectamus. — Мы рассматриваем длинные рога.",
		},
		{
			"name": "Вертела греются в огне.",
			"id": "latinN_4_NO_p_5197848c",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Verua in igne calent. — Вертела греются в огне.",
			"test": "<…> Verua in igne calent. — Вертела греются в огне.",
		},
		{
			"name": "Вкусы плодов сладкие.",
			"id": "latinN_4_GE_p_17f052a3",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Sapores fructuum dulces sunt. — Вкусы плодов сладкие.",
			"test": "<…> Sapores fructuum dulces sunt. — Вкусы плодов сладкие.",
		},
		{
			"name": "Природа духов неясна.",
			"id": "latinN_4_GE_p_2e0fa5d3",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Natura spirituum obscura est. — Природа духов неясна.",
			"test": "<…> Natura spirituum obscura est. — Природа духов неясна.",
		},
		{
			"name": "Красота рук восхитительна.",
			"id": "latinN_4_GE_p_5010be6",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Pulchritudo manuum admirabilis est. — Красота рук восхитительна.",
			"test": "<…> Pulchritudo manuum admirabilis est. — Красота рук восхитительна.",
		},
		{
			"name": "Высота колен мала.",
			"id": "latinN_4_GE_p_685f4c2e",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Altitudo genuum parva est. — Высота колен мала.",
			"test": "<…> Altitudo genuum parva est. — Высота колен мала.",
		},
		{
			"name": "Длина рогов велика.",
			"id": "latinN_4_GE_p_7daf6ecc",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Longitudo cornuum magna est. — Длина рогов велика.",
			"test": "<…> Longitudo cornuum magna est. — Длина рогов велика.",
		},
		{
			"name": "Использование вертел необходимо.",
			"id": "latinN_4_GE_p_2e5d6d97",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Usus veruum necessarius est. — Использование вертел необходимо.",
			"test": "<…> Usus veruum necessarius est. — Использование вертел необходимо.",
		},
		{
			"name": "Цвета плодов разнообразные.",
			"id": "latinN_4_GE_p_238e0d81",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Colores fructuum varii sunt. — Цвета плодов разнообразные.",
			"test": "<…> Colores fructuum varii sunt. — Цвета плодов разнообразные.",
		},
		{
			"name": "Память духов долгая.",
			"id": "latinN_4_GE_p_31221be2",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Memoria spirituum longa est. — Память духов долгая.",
			"test": "<…> Memoria spirituum longa est. — Память духов долгая.",
		},
		{
			"name": "Ловкость рук очень велика.",
			"id": "latinN_4_GE_p_377dca04",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Agilitas manuum maxima est. — Ловкость рук очень велика.",
			"test": "<…> Agilitas manuum maxima est. — Ловкость рук очень велика.",
		},
		{
			"name": "Прочность колен крепкая.",
			"id": "latinN_4_GE_p_728938a9",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Firmitas genuum valida est. — Прочность колен крепкая.",
			"test": "<…> Firmitas genuum valida est. — Прочность колен крепкая.",
		},
		{
			"name": "Сила рогов восхитительна.",
			"id": "latinN_4_GE_p_21b8d17c",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fortitudo cornuum admirabilis est. — Сила рогов восхитительна.",
			"test": "<…> Fortitudo cornuum admirabilis est. — Сила рогов восхитительна.",
		},
		{
			"name": "Полезность вертел велика.",
			"id": "latinN_4_GE_p_6433a2",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Utilitas veruum magna est. — Полезность вертел велика.",
			"test": "<…> Utilitas veruum magna est. — Полезность вертел велика.",
		},
		{
			"name": "Запахи плодов приятны.",
			"id": "latinN_4_GE_p_5910e440",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Odores fructuum suaves sunt. — Запахи плодов приятны.",
			"test": "<…> Odores fructuum suaves sunt. — Запахи плодов приятны.",
		},
		{
			"name": "Мощь духов велика.",
			"id": "latinN_4_GE_p_6267c3bb",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Potentia spirituum magna est. — Мощь духов велика.",
			"test": "<…> Potentia spirituum magna est. — Мощь духов велика.",
		},
		{
			"name": "Дары плодам малы.",
			"id": "latinN_4_DA_p_533ddba",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Dona fructibus parva sunt. — Дары плодам малы.",
			"test": "<…> Dona fructibus parva sunt. — Дары плодам малы.",
		},
		{
			"name": "Я даю советы духам.",
			"id": "latinN_4_DA_p_246b179d",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Consilia spiritibus do. — Я даю советы духам.",
			"test": "<…> Consilia spiritibus do. — Я даю советы духам.",
		},
		{
			"name": "Помощь рукам необходима.",
			"id": "latinN_4_DA_p_7a07c5b4",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Auxilia manibus opus sunt. — Помощь рукам необходима.",
			"test": "<…> Auxilia manibus opus sunt. — Помощь рукам необходима.",
		},
		{
			"name": "Благополучие колен наилучшее.",
			"id": "latinN_4_DA_p_26a1ab54",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Salutes genuis optima sunt. — Благополучие колен наилучшее.",
			"test": "<…> Salutes genuis optima sunt. — Благополучие колен наилучшее.",
		},
		{
			"name": "Почести причитаются рогам.",
			"id": "latinN_4_DA_p_3d646c37",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Honores cornibus debentur. — Почести причитаются рогам.",
			"test": "<…> Honores cornibus debentur. — Почести причитаются рогам.",
		},
		{
			"name": "Мы служим использованию вертел.",
			"id": "latinN_4_DA_p_41cf53f9",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Usui veribus servimus. — Мы служим использованию вертел.",
			"test": "<…> Usui veribus servimus. — Мы служим использованию вертел.",
		},
		{
			"name": "Награды обещаны плодам.",
			"id": "latinN_4_DA_p_5a10411",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Praemia fructibus promittuntur. — Награды обещаны плодам.",
			"test": "<…> Praemia fructibus promittuntur. — Награды обещаны плодам.",
		},
		{
			"name": "Слова говорятся духам.",
			"id": "latinN_4_DA_p_2ef1e4fa",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Verba spiritibus dicuntur. — Слова говорятся духам.",
			"test": "<…> Verba spiritibus dicuntur. — Слова говорятся духам.",
		},
		{
			"name": "Украшения даются рукам.",
			"id": "latinN_4_DA_p_306a30c7",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Ornamenta manibus dantur. — Украшения даются рукам.",
			"test": "<…> Ornamenta manibus dantur. — Украшения даются рукам.",
		},
		{
			"name": "Лечение колен необходимо.",
			"id": "latinN_4_DA_p_b81eda8",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Curationes genuis necessariae sunt. — Лечение колен необходимо.",
			"test": "<…> Curationes genuis necessariae sunt. — Лечение колен необходимо.",
		},
		{
			"name": "Хвала возносится рогам.",
			"id": "latinN_4_DA_p_68de145",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Laudes cornibus aguntur. — Хвала возносится рогам.",
			"test": "<…> Laudes cornibus aguntur. — Хвала возносится рогам.",
		},
		{
			"name": "Инструменты для вертел приготовлены.",
			"id": "latinN_4_DA_p_27fa135a",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Instrumenta veribus parata sunt. — Инструменты для вертел приготовлены.",
			"test": "<…> Instrumenta veribus parata sunt. — Инструменты для вертел приготовлены.",
		},
		{
			"name": "Благодарности возносятся плодам.",
			"id": "latinN_4_DA_p_46f7f36a",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Gratiae fructibus aguntur. — Благодарности возносятся плодам.",
			"test": "<…> Gratiae fructibus aguntur. — Благодарности возносятся плодам.",
		},
		{
			"name": "Книги передаются духам.",
			"id": "latinN_4_DA_p_421faab1",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Libri spiritibus traduntur. — Книги передаются духам.",
			"test": "<…> Libri spiritibus traduntur. — Книги передаются духам.",
		},
		{
			"name": "Здоровье рук наилучшее.",
			"id": "latinN_4_DA_p_2b71fc7e",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Sanitates manibus optima sunt. — Здоровье рук наилучшее.",
			"test": "<…> Sanitates manibus optima sunt. — Здоровье рук наилучшее.",
		},
		{
			"name": "Лекарства для колен приготовлены.",
			"id": "latinN_4_DA_p_5ce65a89",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Remedia genuis parata sunt. — Лекарства для колен приготовлены.",
			"test": "<…> Remedia genuis parata sunt. — Лекарства для колен приготовлены.",
		},
		{
			"name": "Я вижу плоды на деревьях.",
			"id": "latinN_4_AC_p_25f38edc",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fructus in arboribus video. — Я вижу плоды на деревьях.",
			"test": "<…> Fructus in arboribus video. — Я вижу плоды на деревьях.",
		},
		{
			"name": "Мы поклоняемся святым духам.",
			"id": "latinN_4_AC_p_1a86f2f1",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Spiritus sanctos adoramus. — Мы поклоняемся святым духам.",
			"test": "<…> Spiritus sanctos adoramus. — Мы поклоняемся святым духам.",
		},
		{
			"name": "Мы хвалим прекрасные руки.",
			"id": "latinN_4_AC_p_3eb07fd3",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Manus pulchras laudamus. — Мы хвалим прекрасные руки.",
			"test": "<…> Manus pulchras laudamus. — Мы хвалим прекрасные руки.",
		},
		{
			"name": "Мы лечим сломанные колени.",
			"id": "latinN_4_AC_p_506c589e",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Genua fracta curamus. — Мы лечим сломанные колени.",
			"test": "<…> Genua fracta curamus. — Мы лечим сломанные колени.",
		},
		{
			"name": "Мы удивляемся длинным рогам.",
			"id": "latinN_4_AC_p_69d0a921",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Cornua longa miramur. — Мы удивляемся длинным рогам.",
			"test": "<…> Cornua longa miramur. — Мы удивляемся длинным рогам.",
		},
		{
			"name": "Мы получаем новые вертела.",
			"id": "latinN_4_AC_p_446cdf90",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Verua nova accipimus. — Мы получаем новые вертела.",
			"test": "<…> Verua nova accipimus. — Мы получаем новые вертела.",
		},
		{
			"name": "Мы едим сладкие плоды.",
			"id": "latinN_4_AC_p_799f7e29",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fructus dulces edimus. — Мы едим сладкие плоды.",
			"test": "<…> Fructus dulces edimus. — Мы едим сладкие плоды.",
		},
		{
			"name": "Мы любим добрых духов.",
			"id": "latinN_4_AC_p_4b85612c",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Spiritus bonos amamus. — Мы любим добрых духов.",
			"test": "<…> Spiritus bonos amamus. — Мы любим добрых духов.",
		},
		{
			"name": "Мы приветствуем работающие руки.",
			"id": "latinN_4_AC_p_277050dc",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Manus laborantes salutamus. — Мы приветствуем работающие руки.",
			"test": "<…> Manus laborantes salutamus. — Мы приветствуем работающие руки.",
		},
		{
			"name": "Крепкие колени восхваляются.",
			"id": "latinN_4_AC_p_5c29bfd",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Genua valida laudantur. — Крепкие колени восхваляются.",
			"test": "<…> Genua valida laudantur. — Крепкие колени восхваляются.",
		},
		{
			"name": "Мы рассматриваем большие рога.",
			"id": "latinN_4_AC_p_7aec35a",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Cornua magna spectamus. — Мы рассматриваем большие рога.",
			"test": "<…> Cornua magna spectamus. — Мы рассматриваем большие рога.",
		},
		{
			"name": "Мы осторожны с горячими вертелами.",
			"id": "latinN_4_AC_p_67424e82",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Verua calida cauti sumus. — Мы осторожны с горячими вертелами.",
			"test": "<…> Verua calida cauti sumus. — Мы осторожны с горячими вертелами.",
		},
		{
			"name": "Мы срываем зрелые плоды.",
			"id": "latinN_4_AC_p_42110406",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fructus maturi carpimus. — Мы срываем зрелые плоды.",
			"test": "<…> Fructus maturi carpimus. — Мы срываем зрелые плоды.",
		},
		{
			"name": "Мы боимся злых духов.",
			"id": "latinN_4_AC_p_531d72ca",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Spiritus mali timemus. — Мы боимся злых духов.",
			"test": "<…> Spiritus mali timemus. — Мы боимся злых духов.",
		},
		{
			"name": "Мы держим правые руки.",
			"id": "latinN_4_AC_p_22d8cfe0",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Manus dextras tenemus. — Мы держим правые руки.",
			"test": "<…> Manus dextras tenemus. — Мы держим правые руки.",
		},
		{
			"name": "Больные колени лечатся.",
			"id": "latinN_4_AC_p_579bb367",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Genua dolentia curantur. — Больные колени лечатся.",
			"test": "<…> Genua dolentia curantur. — Больные колени лечатся.",
		},
		{
			"name": "Мы радуемся сладким плодам.",
			"id": "latinN_4_AB_p_1de0aca6",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fructibus dulcibus gaudemus. — Мы радуемся сладким плодам.",
			"test": "<…> Fructibus dulcibus gaudemus. — Мы радуемся сладким плодам.",
		},
		{
			"name": "Мы защищены святыми духами.",
			"id": "latinN_4_AB_p_255316f2",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "A spiritibus sanctis protegimur. — Мы защищены святыми духами.",
			"test": "<…> A spiritibus sanctis protegimur. — Мы защищены святыми духами.",
		},
		{
			"name": "Картины рисуются прекрасными руками.",
			"id": "latinN_4_AB_p_41906a77",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Manibus pulchris picturae pinguntur. — Картины рисуются прекрасными руками.",
			"test": "<…> Manibus pulchris picturae pinguntur. — Картины рисуются прекрасными руками.",
		},
		{
			"name": "Со сломанными коленями ходить трудно.",
			"id": "latinN_4_AB_p_4b9af9a9",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Genuis fractis ambulare difficile est. — Со сломанными коленями ходить трудно.",
			"test": "<…> Genuis fractis ambulare difficile est. — Со сломанными коленями ходить трудно.",
		},
		{
			"name": "Быки сражаются крепкими рогами.",
			"id": "latinN_4_AB_p_5387f9e0",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Cornibus validis tauri pugnant. — Быки сражаются крепкими рогами.",
			"test": "<…> Cornibus validis tauri pugnant. — Быки сражаются крепкими рогами.",
		},
		{
			"name": "Мы осторожны с горячими вертелами.",
			"id": "latinN_4_AB_p_6e5e91e4",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Ab veris calidis cauti sumus. — Мы осторожны с горячими вертелами.",
			"test": "<…> Ab veris calidis cauti sumus. — Мы осторожны с горячими вертелами.",
		},
		{
			"name": "Мы насытились зрелыми плодами.",
			"id": "latinN_4_AB_p_2cdf8d8a",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fructibus maturis saturati sumus. — Мы насытились зрелыми плодами.",
			"test": "<…> Fructibus maturis saturati sumus. — Мы насытились зрелыми плодами.",
		},
		{
			"name": "Мы сражаемся с сильным духом.",
			"id": "latinN_4_AB_p_30946e09",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Cum spiritibus fortimus pugnamus. — Мы сражаемся с сильным духом.",
			"test": "<…> Cum spiritibus fortimus pugnamus. — Мы сражаемся с сильным духом.",
		},
		{
			"name": "Мы пишем правыми руками.",
			"id": "latinN_4_AB_p_5cb0d902",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Manibus dexteris scribimus. — Мы пишем правыми руками.",
			"test": "<…> Manibus dexteris scribimus. — Мы пишем правыми руками.",
		},
		{
			"name": "Они встали с больных колен.",
			"id": "latinN_4_AB_p_46fbb2c1",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "E genuis dolentibus surrexerunt. — Они встали с больных колен.",
			"test": "<…> E genuis dolentibus surrexerunt. — Они встали с больных колен.",
		},
		{
			"name": "Быки пугают острыми рогами.",
			"id": "latinN_4_AB_p_1698c449",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Cornibus acutis tauri terrent. — Быки пугают острыми рогами.",
			"test": "<…> Cornibus acutis tauri terrent. — Быки пугают острыми рогами.",
		},
		{
			"name": "Мы пользуемся новыми вертелами.",
			"id": "latinN_4_AB_p_5ef04b5",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Veris novis utimur. — Мы пользуемся новыми вертелами.",
			"test": "<…> Veris novis utimur. — Мы пользуемся новыми вертелами.",
		},
		{
			"name": "Мы радуемся новым плодам.",
			"id": "latinN_4_AB_p_5f4da5c3",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Fructibus novis gaudemus. — Мы радуемся новым плодам.",
			"test": "<…> Fructibus novis gaudemus. — Мы радуемся новым плодам.",
		},
		{
			"name": "Мы защищаемся от злых духов.",
			"id": "latinN_4_AB_p_443b7951",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "A spiritibus malignis defendimur. — Мы защищаемся от злых духов.",
			"test": "<…> A spiritibus malignis defendimur. — Мы защищаемся от злых духов.",
		},
		{
			"name": "Мы держим левой рукой.",
			"id": "latinN_4_AB_p_14514713",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Manibus sinistris tenemus. — Мы держим левой рукой.",
			"test": "<…> Manibus sinistris tenemus. — Мы держим левой рукой.",
		},
		{
			"name": "Мы ходим с помощью крепких колен.",
			"id": "latinN_4_AB_p_69663380",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Per genua valida ambulamus. — Мы ходим с помощью крепких колен.",
			"test": "<…> Per genua valida ambulamus. — Мы ходим с помощью крепких колен.",
		},
		{
			"name": "Быки гордятся большими рогами.",
			"id": "latinN_4_AB_p_5b37e0d2",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Cornibus magnis tauri gloriantur. — Быки гордятся большими рогами.",
			"test": "<…> Cornibus magnis tauri gloriantur. — Быки гордятся большими рогами.",
		},
		{
			"name": "Будьте осторожны с нагретыми вертелами.",
			"id": "latinN_4_AB_p_4459eb14",
			"grade": "latin_noun",
			"letters": ["4"],
			"full": "Veris calentibus cauti estote. — Будьте осторожны с нагретыми вертелами.",
			"test": "<…> Veris calentibus cauti estote. — Будьте осторожны с нагретыми вертелами.",
		}
	);
}
