/*
* Copyright (c) AParovyshnaya 2020-2026
* 
* AParovyshnaya and theirs affiliates make no warranty of any kind
* with regard to this material. 
* 
* AParovyshnaya expressly disclaims all warranties as to the material, express, 
* and implied, including but not limited to the implied warranties of 
* merchantability, fitness for a particular purpose and non-infringement of third 
* party rights. 
* 
* In no event shall AParovyshnaya be liable to you or any other person for any damages, 
* including, without limitation, any direct, indirect, incidental or consequential 
* damages, expenses, lost profits, lost data or other damages arising out of the use, 
* misuse or inability to use the material and any derived software, even if AParovyshnaya, 
* their affiliate or an authorized dealer has been advised of the possibility of such damages. 
* 
*/

export function withLatinNoun2Tests() {
	data.data.push(
		// singular
		{
			"name": "Раб работает в вилле.",
			"id": "latinN_2_NO_s_49c2faae",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Servus in villa laborat. — Раб работает в вилле.",
			"test": "<…> Servus in villa laborat. — Раб работает в вилле.",
		},
		{
			"name": "Мальчик бежит на дороге.",
			"id": "latinN_2_NO_s_20ad9418",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Puer in via currit. — Мальчик бежит на дороге.",
			"test": "<…> Puer in via currit. — Мальчик бежит на дороге.",
		},
		{
			"name": "Конь пасётся в поле.",
			"id": "latinN_2_NO_s_31cefde0",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Equus in campo pascitur. — Конь пасётся в поле.",
			"test": "<…> Equus in campo pascitur. — Конь пасётся в поле.",
		},
		{
			"name": "Подарок прекрасен.",
			"id": "latinN_2_NO_s_439f5b3d",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Donum pulchrum est. — Подарок прекрасен.",
			"test": "<…> Donum pulchrum est. — Подарок прекрасен.",
		},
		{
			"name": "Слово истинно.",
			"id": "latinN_2_NO_s_1d56ce6a",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Verbum verum est. — Слово истинно.",
			"test": "<…> Verbum verum est. — Слово истинно.",
		},
		{
			"name": "Храм велик.",
			"id": "latinN_2_NO_s_5197848c",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Templum magnum est. — Храм велик.",
			"test": "<…> Templum magnum est. — Храм велик.",
		},
		{
			"name": "Дом раба мал.",
			"id": "latinN_2_GE_s_17f052a3",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Domus servi parva est. — Дом раба мал.",
			"test": "<…> Domus servi parva est. — Дом раба мал.",
		},
		{
			"name": "Книга мальчика новая.",
			"id": "latinN_2_GE_s_2e0fa5d3",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Liber pueri novus est. — Книга мальчика новая.",
			"test": "<…> Liber pueri novus est. — Книга мальчика новая.",
		},
		{
			"name": "Грива коня длинная.",
			"id": "latinN_2_GE_s_5010be6",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Capillus equi longus est. — Грива коня длинная.",
			"test": "<…> Capillus equi longus est. — Грива коня длинная.",
		},
		{
			"name": "Ценность подарка велика.",
			"id": "latinN_2_GE_s_685f4c2e",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Valor doni magnus est. — Ценность подарка велика.",
			"test": "<…> Valor doni magnus est. — Ценность подарка велика.",
		},
		{
			"name": "Начало слова хорошее.",
			"id": "latinN_2_GE_s_7daf6ecc",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Initium verbi bonum est. — Начало слова хорошее.",
			"test": "<…> Initium verbi bonum est. — Начало слова хорошее.",
		},
		{
			"name": "Алтарь храма священный.",
			"id": "latinN_2_GE_s_2e5d6d97",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Ara templi sacra est. — Алтарь храма священный.",
			"test": "<…> Ara templi sacra est. — Алтарь храма священный.",
		},
		{
			"name": "Друг раба верный.",
			"id": "latinN_2_GE_s_238e0d81",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Amicus servi fidus est. — Друг раба верный.",
			"test": "<…> Amicus servi fidus est. — Друг раба верный.",
		},
		{
			"name": "Имя мальчика — Марк.",
			"id": "latinN_2_GE_s_31221be2",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Nomen pueri Marcus est. — Имя мальчика — Марк.",
			"test": "<…> Nomen pueri Marcus est. — Имя мальчика — Марк.",
		},
		{
			"name": "Шея коня красивая.",
			"id": "latinN_2_GE_s_377dca04",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Collum equi bellum est. — Шея коня красивая.",
			"test": "<…> Collum equi bellum est. — Шея коня красивая.",
		},
		{
			"name": "Украшение подарка великолепное.",
			"id": "latinN_2_GE_s_728938a9",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Ornamentum doni splendidum est. — Украшение подарка великолепное.",
			"test": "<…> Ornamentum doni splendidum est. — Украшение подарка великолепное.",
		},
		{
			"name": "Звук слова ясный.",
			"id": "latinN_2_GE_s_21b8d17c",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Sonus verbi clarus est. — Звук слова ясный.",
			"test": "<…> Sonus verbi clarus est. — Звук слова ясный.",
		},
		{
			"name": "Дверь храма открыта.",
			"id": "latinN_2_GE_s_6433a2",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Porta templi aperta est. — Дверь храма открыта.",
			"test": "<…> Porta templi aperta est. — Дверь храма открыта.",
		},
		{
			"name": "Семья раба живёт в городе.",
			"id": "latinN_2_GE_s_5910e440",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Familia servi in urbe habitat. — Семья раба живёт в городе.",
			"test": "<…> Familia servi in urbe habitat. — Семья раба живёт в городе.",
		},
		{
			"name": "Игра мальчика в саду.",
			"id": "latinN_2_GE_s_6267c3bb",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Ludus pueri in horto est. — Игра мальчика в саду.",
			"test": "<…> Ludus pueri in horto est. — Игра мальчика в саду.",
		},
		{
			"name": "Я даю подарок рабу.",
			"id": "latinN_2_DA_s_533ddba",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Donum servo do. — Я даю подарок рабу.",
			"test": "<…> Donum servo do. — Я даю подарок рабу.",
		},
		{
			"name": "Книжечка даётся мальчику.",
			"id": "latinN_2_DA_s_246b179d",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Libellus puero datur. — Книжечка даётся мальчику.",
			"test": "<…> Libellus puero datur. — Книжечка даётся мальчику.",
		},
		{
			"name": "Еда предлагается коню.",
			"id": "latinN_2_DA_s_7a07c5b4",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Cibus equo offertur. — Еда предлагается коню.",
			"test": "<…> Cibus equo offertur. — Еда предлагается коню.",
		},
		{
			"name": "Почесть воздаётся подарку.",
			"id": "latinN_2_DA_s_26a1ab54",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Honor dono tribuitur. — Почесть воздаётся подарку.",
			"test": "<…> Honor dono tribuitur. — Почесть воздаётся подарку.",
		},
		{
			"name": "Значение добавляется слову.",
			"id": "latinN_2_DA_s_3d646c37",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Significatio verbo additur. — Значение добавляется слову.",
			"test": "<…> Significatio verbo additur. — Значение добавляется слову.",
		},
		{
			"name": "Жертвоприношение совершается храму.",
			"id": "latinN_2_DA_s_41cf53f9",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Sacrificium templo fit. — Жертвоприношение совершается храму.",
			"test": "<…> Sacrificium templo fit. — Жертвоприношение совершается храму.",
		},
		{
			"name": "Награда обещана рабу.",
			"id": "latinN_2_DA_s_5a10411",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Praemium servo promittitur. — Награда обещана рабу.",
			"test": "<…> Praemium servo promittitur. — Награда обещана рабу.",
		},
		{
			"name": "Игра нравится мальчику.",
			"id": "latinN_2_DA_s_2ef1e4fa",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Ludus puero placet. — Игра нравится мальчику.",
			"test": "<…> Ludus puero placet. — Игра нравится мальчику.",
		},
		{
			"name": "Вода должна быть выпита конём.",
			"id": "latinN_2_DA_s_306a30c7",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Aqua equo bibenda est. — Вода должна быть выпита конём.",
			"test": "<…> Aqua equo bibenda est. — Вода должна быть выпита конём.",
		},
		{
			"name": "Хвала причитается подарку.",
			"id": "latinN_2_DA_s_b81eda8",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Laus dono debetur. — Хвала причитается подарку.",
			"test": "<…> Laus dono debetur. — Хвала причитается подарку.",
		},
		{
			"name": "Мысль подходит слову.",
			"id": "latinN_2_DA_s_68de145",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Sententia verbo apta est. — Мысль подходит слову.",
			"test": "<…> Sententia verbo apta est. — Мысль подходит слову.",
		},
		{
			"name": "Обет возносится храму.",
			"id": "latinN_2_DA_s_27fa135a",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Votum templo offertur. — Обет возносится храму.",
			"test": "<…> Votum templo offertur. — Обет возносится храму.",
		},
		{
			"name": "Помощь нужна рабу.",
			"id": "latinN_2_DA_s_46f7f36a",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Auxilium servo opus est. — Помощь нужна рабу.",
			"test": "<…> Auxilium servo opus est. — Помощь нужна рабу.",
		},
		{
			"name": "Слова говорятся мальчику.",
			"id": "latinN_2_DA_s_421faab1",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Verba puero dicuntur. — Слова говорятся мальчику.",
			"test": "<…> Verba puero dicuntur. — Слова говорятся мальчику.",
		},
		{
			"name": "Корм приготовлен для коня.",
			"id": "latinN_2_DA_s_2b71fc7e",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Pabulum equo paratum est. — Корм приготовлен для коня.",
			"test": "<…> Pabulum equo paratum est. — Корм приготовлен для коня.",
		},
		{
			"name": "Благодарности возносятся подарку.",
			"id": "latinN_2_DA_s_5ce65a89",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Gratiae dono aguntur. — Благодарности возносятся подарку.",
			"test": "<…> Gratiae dono aguntur. — Благодарности возносятся подарку.",
		},
		{
			"name": "Я вижу раба в поле.",
			"id": "latinN_2_AC_s_25f38edc",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Servum in agro video. — Я вижу раба в поле.",
			"test": "<…> Servum in agro video. — Я вижу раба в поле.",
		},
		{
			"name": "Я приветствую мальчика в школе.",
			"id": "latinN_2_AC_s_1a86f2f1",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Puerum in ludo saluto. — Я приветствую мальчика в школе.",
			"test": "<…> Puerum in ludo saluto. — Я приветствую мальчика в школе.",
		},
		{
			"name": "Я наблюдаю коня на дороге.",
			"id": "latinN_2_AC_s_3eb07fd3",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Equum in via observo. — Я наблюдаю коня на дороге.",
			"test": "<…> Equum in via observo. — Я наблюдаю коня на дороге.",
		},
		{
			"name": "Я получаю подарок от матери.",
			"id": "latinN_2_AC_s_506c589e",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Donum a matre accipio. — Я получаю подарок от матери.",
			"test": "<…> Donum a matre accipio. — Я получаю подарок от матери.",
		},
		{
			"name": "Я слышу слово от друга.",
			"id": "latinN_2_AC_s_69d0a921",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Verbum ab amico audio. — Я слышу слово от друга.",
			"test": "<…> Verbum ab amico audio. — Я слышу слово от друга.",
		},
		{
			"name": "Я рассматриваю храм на холме.",
			"id": "latinN_2_AC_s_446cdf90",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Templum in colle specto. — Я рассматриваю храм на холме.",
			"test": "<…> Templum in colle specto. — Я рассматриваю храм на холме.",
		},
		{
			"name": "Мы ведём раба к вилле.",
			"id": "latinN_2_AC_s_799f7e29",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Servum ad villam ducimus. — Мы ведём раба к вилле.",
			"test": "<…> Servum ad villam ducimus. — Мы ведём раба к вилле.",
		},
		{
			"name": "Мы приветствуем мальчика с похвалой.",
			"id": "latinN_2_AC_s_4b85612c",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Puerum cum laude salutamus. — Мы приветствуем мальчика с похвалой.",
			"test": "<…> Puerum cum laude salutamus. — Мы приветствуем мальчика с похвалой.",
		},
		{
			"name": "Земледелец ведёт коня к воде.",
			"id": "latinN_2_AC_s_277050dc",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Equum ad aquam ducit agricola. — Земледелец ведёт коня к воде.",
			"test": "<…> Equum ad aquam ducit agricola. — Земледелец ведёт коня к воде.",
		},
		{
			"name": "Он передаёт мне большой подарок.",
			"id": "latinN_2_AC_s_5c29bfd",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Donum magnum mihi tradit. — Он передаёт мне большой подарок.",
			"test": "<…> Donum magnum mihi tradit. — Он передаёт мне большой подарок.",
		},
		{
			"name": "Мы учим новое слово.",
			"id": "latinN_2_AC_s_7aec35a",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Verbum novum discimus. — Мы учим новое слово.",
			"test": "<…> Verbum novum discimus. — Мы учим новое слово.",
		},
		{
			"name": "Мы посещаем священный храм.",
			"id": "latinN_2_AC_s_67424e82",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Templum sacrum visitamus. — Мы посещаем священный храм.",
			"test": "<…> Templum sacrum visitamus. — Мы посещаем священный храм.",
		},
		{
			"name": "Я вижу работающего раба.",
			"id": "latinN_2_AC_s_42110406",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Servum laborantem video. — Я вижу работающего раба.",
			"test": "<…> Servum laborantem video. — Я вижу работающего раба.",
		},
		{
			"name": "Я приветствую играющего мальчика.",
			"id": "latinN_2_AC_s_531d72ca",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Puerum ludentem saluto. — Я приветствую играющего мальчика.",
			"test": "<…> Puerum ludentem saluto. — Я приветствую играющего мальчика.",
		},
		{
			"name": "Он приказывает коню бежать.",
			"id": "latinN_2_AC_s_22d8cfe0",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Equum currere iubet. — Он приказывает коню бежать.",
			"test": "<…> Equum currere iubet. — Он приказывает коню бежать.",
		},
		{
			"name": "Ты получаешь маленький подарок.",
			"id": "latinN_2_AC_s_579bb367",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Donum parvum accipis. — Ты получаешь маленький подарок.",
			"test": "<…> Donum parvum accipis. — Ты получаешь маленький подарок.",
		},
		{
			"name": "Раб хвалится господином.",
			"id": "latinN_2_AB_s_1de0aca6",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Servo a domino laudatur. — Раб хвалится господином.",
			"test": "<…> Servo a domino laudatur. — Раб хвалится господином.",
		},
		{
			"name": "Мальчик ведётся другом.",
			"id": "latinN_2_AB_s_255316f2",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Puer ab amico ducitur. — Мальчик ведётся другом.",
			"test": "<…> Puer ab amico ducitur. — Мальчик ведётся другом.",
		},
		{
			"name": "Конь ухаживается пастухом.",
			"id": "latinN_2_AB_s_41906a77",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Equo a pastore curatur. — Конь ухаживается пастухом.",
			"test": "<…> Equo a pastore curatur. — Конь ухаживается пастухом.",
		},
		{
			"name": "Мы радуемся подарку, посланному другом.",
			"id": "latinN_2_AB_s_4b9af9a9",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Dono ab amico missum gaudemus. — Мы радуемся подарку, посланному другом.",
			"test": "<…> Dono ab amico missum gaudemus. — Мы радуемся подарку, посланному другом.",
		},
		{
			"name": "Мы поражены словом, произнесённым оратором.",
			"id": "latinN_2_AB_s_5387f9e0",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Verbo ab oratore pronuntiato attoniti sumus. — Мы поражены словом, произнесённым оратором.",
			"test": "<…> Verbo ab oratore pronuntiato attoniti sumus. — Мы поражены словом, произнесённым оратором.",
		},
		{
			"name": "Мы восхищаемся храмом, построенным древними.",
			"id": "latinN_2_AB_s_6e5e91e4",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Templo ab antiquis aedificato miramur. — Мы восхищаемся храмом, построенным древними.",
			"test": "<…> Templo ab antiquis aedificato miramur. — Мы восхищаемся храмом, построенным древними.",
		},
		{
			"name": "Раб работает с верностью.",
			"id": "latinN_2_AB_s_2cdf8d8a",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Servo cum fide laborat. — Раб работает с верностью.",
			"test": "<…> Servo cum fide laborat. — Раб работает с верностью.",
		},
		{
			"name": "Мальчик играет с друзьями.",
			"id": "latinN_2_AB_s_30946e09",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Puer cum amicis ludit. — Мальчик играет с друзьями.",
			"test": "<…> Puer cum amicis ludit. — Мальчик играет с друзьями.",
		},
		{
			"name": "Земледелец работает с конём и плугом.",
			"id": "latinN_2_AB_s_5cb0d902",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Equo cum aratro laborat agricola. — Земледелец работает с конём и плугом.",
			"test": "<…> Equo cum aratro laborat agricola. — Земледелец работает с конём и плугом.",
		},
		{
			"name": "Мы пользуемся подарком с радостью.",
			"id": "latinN_2_AB_s_46fbb2c1",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Dono cum gaudio utimur. — Мы пользуемся подарком с радостью.",
			"test": "<…> Dono cum gaudio utimur. — Мы пользуемся подарком с радостью.",
		},
		{
			"name": "Он пользуется словом с осторожностью.",
			"id": "latinN_2_AB_s_1698c449",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Verbo cum cura utitur. — Он пользуется словом с осторожностью.",
			"test": "<…> Verbo cum cura utitur. — Он пользуется словом с осторожностью.",
		},
		{
			"name": "Мы приближаемся к храму с почтением.",
			"id": "latinN_2_AB_s_5ef04b5",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Templo cum reverentia appropinquamus. — Мы приближаемся к храму с почтением.",
			"test": "<…> Templo cum reverentia appropinquamus. — Мы приближаемся к храму с почтением.",
		},
		{
			"name": "Раб устал от работы.",
			"id": "latinN_2_AB_s_5f4da5c3",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Servo ab opere defessus est. — Раб устал от работы.",
			"test": "<…> Servo ab opere defessus est. — Раб устал от работы.",
		},
		{
			"name": "Мальчик возвращается из школы.",
			"id": "latinN_2_AB_s_443b7951",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Puer e ludo revenit. — Мальчик возвращается из школы.",
			"test": "<…> Puer e ludo revenit. — Мальчик возвращается из школы.",
		},
		{
			"name": "Конь бежит через поле.",
			"id": "latinN_2_AB_s_14514713",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Equo per campum currit. — Конь бежит через поле.",
			"test": "<…> Equo per campum currit. — Конь бежит через поле.",
		},
		{
			"name": "Он радуется подарку, полученному от матери.",
			"id": "latinN_2_AB_s_69663380",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Dono a matre accepto gaudet. — Он радуется подарку, полученному от матери.",
			"test": "<…> Dono a matre accepto gaudet. — Он радуется подарку, полученному от матери.",
		},
		// plural
		{
			"name": "Рабы работают в вилле.",
			"id": "latinN_2_NO_p_49c2faae",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Servi in villa laborant. — Рабы работают в вилле.",
			"test": "<…> Servi in villa laborant. — Рабы работают в вилле.",
		},
		{
			"name": "Мальчики бегут на дороге.",
			"id": "latinN_2_NO_p_20ad9418",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Pueri in via currunt. — Мальчики бегут на дороге.",
			"test": "<…> Pueri in via currunt. — Мальчики бегут на дороге.",
		},
		{
			"name": "Кони пасутся в поле.",
			"id": "latinN_2_NO_p_31cefde0",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Equi in campo pascuntur. — Кони пасутся в поле.",
			"test": "<…> Equi in campo pascuntur. — Кони пасутся в поле.",
		},
		{
			"name": "Подарки прекрасны.",
			"id": "latinN_2_NO_p_439f5b3d",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Dona pulchra sunt. — Подарки прекрасны.",
			"test": "<…> Dona pulchra sunt. — Подарки прекрасны.",
		},
		{
			"name": "Слова истинны.",
			"id": "latinN_2_NO_p_1d56ce6a",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Verba vera sunt. — Слова истинны.",
			"test": "<…> Verba vera sunt. — Слова истинны.",
		},
		{
			"name": "Храмы велики.",
			"id": "latinN_2_NO_p_5197848c",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Templa magna sunt. — Храмы велики.",
			"test": "<…> Templa magna sunt. — Храмы велики.",
		},
		{
			"name": "Дома рабов малы.",
			"id": "latinN_2_GE_p_17f052a3",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Domus servorum parvae sunt. — Дома рабов малы.",
			"test": "<…> Domus servorum parvae sunt. — Дома рабов малы.",
		},
		{
			"name": "Книги мальчиков новые.",
			"id": "latinN_2_GE_p_2e0fa5d3",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Libri puerorum novi sunt. — Книги мальчиков новые.",
			"test": "<…> Libri puerorum novi sunt. — Книги мальчиков новые.",
		},
		{
			"name": "Гривы коней длинные.",
			"id": "latinN_2_GE_p_5010be6",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Capilli equorum longi sunt. — Гривы коней длинные.",
			"test": "<…> Capilli equorum longi sunt. — Гривы коней длинные.",
		},
		{
			"name": "Ценности подарков велики.",
			"id": "latinN_2_GE_p_685f4c2e",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Valores donorum magnī sunt. — Ценности подарков велики.",
			"test": "<…> Valores donorum magnī sunt. — Ценности подарков велики.",
		},
		{
			"name": "Начала слов хорошие.",
			"id": "latinN_2_GE_p_7daf6ecc",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Initia verborum bona sunt. — Начала слов хорошие.",
			"test": "<…> Initia verborum bona sunt. — Начала слов хорошие.",
		},
		{
			"name": "Алтари храмов священные.",
			"id": "latinN_2_GE_p_2e5d6d97",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Arae templorum sacrae sunt. — Алтари храмов священные.",
			"test": "<…> Arae templorum sacrae sunt. — Алтари храмов священные.",
		},
		{
			"name": "Друзья рабов верные.",
			"id": "latinN_2_GE_p_238e0d81",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Amici servorum fidi sunt. — Друзья рабов верные.",
			"test": "<…> Amici servorum fidi sunt. — Друзья рабов верные.",
		},
		{
			"name": "Имена мальчиков известные.",
			"id": "latinN_2_GE_p_31221be2",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Nomina puerorum nota sunt. — Имена мальчиков известные.",
			"test": "<…> Nomina puerorum nota sunt. — Имена мальчиков известные.",
		},
		{
			"name": "Шеи коней красивые.",
			"id": "latinN_2_GE_p_377dca04",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Colla equorum bella sunt. — Шеи коней красивые.",
			"test": "<…> Colla equorum bella sunt. — Шеи коней красивые.",
		},
		{
			"name": "Украшения подарков великолепные.",
			"id": "latinN_2_GE_p_728938a9",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Ornamenta donorum splendida sunt. — Украшения подарков великолепные.",
			"test": "<…> Ornamenta donorum splendida sunt. — Украшения подарков великолепные.",
		},
		{
			"name": "Звуки слов ясные.",
			"id": "latinN_2_GE_p_21b8d17c",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Sonī verborum clari sunt. — Звуки слов ясные.",
			"test": "<…> Sonī verborum clari sunt. — Звуки слов ясные.",
		},
		{
			"name": "Двери храмов открыты.",
			"id": "latinN_2_GE_p_6433a2",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Portae templorum apertae sunt. — Двери храмов открыты.",
			"test": "<…> Portae templorum apertae sunt. — Двери храмов открыты.",
		},
		{
			"name": "Семьи рабов живут в городе.",
			"id": "latinN_2_GE_p_5910e440",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Familiarum servorum in urbe habitant. — Семьи рабов живут в городе.",
			"test": "<…> Familiarum servorum in urbe habitant. — Семьи рабов живут в городе.",
		},
		{
			"name": "Игры мальчиков в садах.",
			"id": "latinN_2_GE_p_6267c3bb",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Ludi puerorum in hortis sunt. — Игры мальчиков в садах.",
			"test": "<…> Ludi puerorum in hortis sunt. — Игры мальчиков в садах.",
		},
		{
			"name": "Награды рабов велики.",
			"id": "latinN_2_GE_p_533ddba",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Praemia servorum magna sunt. — Награды рабов велики.",
			"test": "<…> Praemia servorum magna sunt. — Награды рабов велики.",
		},
		{
			"name": "Письмена мальчиков прекрасны.",
			"id": "latinN_2_GE_p_246b179d",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Scripta puerorum pulchra sunt. — Письмена мальчиков прекрасны.",
			"test": "<…> Scripta puerorum pulchra sunt. — Письмена мальчиков прекрасны.",
		},
		{
			"name": "Я даю подарки рабам.",
			"id": "latinN_2_DA_p_7a07c5b4",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Dona servis do. — Я даю подарки рабам.",
			"test": "<…> Dona servis do. — Я даю подарки рабам.",
		},
		{
			"name": "Книжечки даются мальчикам.",
			"id": "latinN_2_DA_p_26a1ab54",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Libelli pueris dantur. — Книжечки даются мальчикам.",
			"test": "<…> Libelli pueris dantur. — Книжечки даются мальчикам.",
		},
		{
			"name": "Еда предлагается коням.",
			"id": "latinN_2_DA_p_3d646c37",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Cibi equis offeruntur. — Еда предлагается коням.",
			"test": "<…> Cibi equis offeruntur. — Еда предлагается коням.",
		},
		{
			"name": "Почести воздаются подаркам.",
			"id": "latinN_2_DA_p_41cf53f9",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Honores donis tribuuntur. — Почести воздаются подаркам.",
			"test": "<…> Honores donis tribuuntur. — Почести воздаются подаркам.",
		},
		{
			"name": "Значения добавляются словам.",
			"id": "latinN_2_DA_p_5a10411",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Significationes verbis adduntur. — Значения добавляются словам.",
			"test": "<…> Significationes verbis adduntur. — Значения добавляются словам.",
		},
		{
			"name": "Жертвоприношения совершаются храмам.",
			"id": "latinN_2_DA_p_2ef1e4fa",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Sacrificia templis fiunt. — Жертвоприношения совершаются храмам.",
			"test": "<…> Sacrificia templis fiunt. — Жертвоприношения совершаются храмам.",
		},
		{
			"name": "Награды обещаны рабам.",
			"id": "latinN_2_DA_p_306a30c7",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Praemia servis promittuntur. — Награды обещаны рабам.",
			"test": "<…> Praemia servis promittuntur. — Награды обещаны рабам.",
		},
		{
			"name": "Игры нравятся мальчикам.",
			"id": "latinN_2_DA_p_b81eda8",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Ludī pueris placent. — Игры нравятся мальчикам.",
			"test": "<…> Ludī pueris placent. — Игры нравятся мальчикам.",
		},
		{
			"name": "Воды должны быть выпиты конями.",
			"id": "latinN_2_DA_p_68de145",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Aquae equis bibendae sunt. — Воды должны быть выпиты конями.",
			"test": "<…> Aquae equis bibendae sunt. — Воды должны быть выпиты конями.",
		},
		{
			"name": "Хвалы причитаются подаркам.",
			"id": "latinN_2_DA_p_27fa135a",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Laudes donis debentur. — Хвалы причитаются подаркам.",
			"test": "<…> Laudes donis debentur. — Хвалы причитаются подаркам.",
		},
		{
			"name": "Мысли подходят словам.",
			"id": "latinN_2_DA_p_46f7f36a",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Sententiae verbis aptae sunt. — Мысли подходят словам.",
			"test": "<…> Sententiae verbis aptae sunt. — Мысли подходят словам.",
		},
		{
			"name": "Обеты возносятся храмам.",
			"id": "latinN_2_DA_p_421faab1",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Vota templis offeruntur. — Обеты возносятся храмам.",
			"test": "<…> Vota templis offeruntur. — Обеты возносятся храмам.",
		},
		{
			"name": "Помощи нужны рабам.",
			"id": "latinN_2_DA_p_2b71fc7e",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Auxilia servis opus sunt. — Помощи нужны рабам.",
			"test": "<…> Auxilia servis opus sunt. — Помощи нужны рабам.",
		},
		{
			"name": "Слова говорятся мальчикам.",
			"id": "latinN_2_DA_p_5ce65a89",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Verba pueris dicuntur. — Слова говорятся мальчикам.",
			"test": "<…> Verba pueris dicuntur. — Слова говорятся мальчикам.",
		},
		{
			"name": "Корма приготовлены для коней.",
			"id": "latinN_2_DA_p_25f38edc",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Pabula equis parata sunt. — Корма приготовлены для коней.",
			"test": "<…> Pabula equis parata sunt. — Корма приготовлены для коней.",
		},
		{
			"name": "Благодарности возносятся подаркам.",
			"id": "latinN_2_DA_p_1a86f2f1",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Gratiae donis aguntur. — Благодарности возносятся подаркам.",
			"test": "<…> Gratiae donis aguntur. — Благодарности возносятся подаркам.",
		},
		{
			"name": "Я вижу рабов в поле.",
			"id": "latinN_2_AC_p_3eb07fd3",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Servos in agro video. — Я вижу рабов в поле.",
			"test": "<…> Servos in agro video. — Я вижу рабов в поле.",
		},
		{
			"name": "Я приветствую мальчиков в школе.",
			"id": "latinN_2_AC_p_506c589e",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Pueros in ludo saluto. — Я приветствую мальчиков в школе.",
			"test": "<…> Pueros in ludo saluto. — Я приветствую мальчиков в школе.",
		},
		{
			"name": "Я наблюдаю коней на дороге.",
			"id": "latinN_2_AC_p_69d0a921",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Equos in via observo. — Я наблюдаю коней на дороге.",
			"test": "<…> Equos in via observo. — Я наблюдаю коней на дороге.",
		},
		{
			"name": "Я получаю подарки от матерей.",
			"id": "latinN_2_AC_p_446cdf90",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Dona a matribus accipio. — Я получаю подарки от матерей.",
			"test": "<…> Dona a matribus accipio. — Я получаю подарки от матерей.",
		},
		{
			"name": "Я слышу слова от друзей.",
			"id": "latinN_2_AC_p_799f7e29",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Verba ab amicis audio. — Я слышу слова от друзей.",
			"test": "<…> Verba ab amicis audio. — Я слышу слова от друзей.",
		},
		{
			"name": "Я рассматриваю храмы на холме.",
			"id": "latinN_2_AC_p_4b85612c",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Templa in colle specto. — Я рассматриваю храмы на холме.",
			"test": "<…> Templa in colle specto. — Я рассматриваю храмы на холме.",
		},
		{
			"name": "Мы ведём рабов к вилле.",
			"id": "latinN_2_AC_p_277050dc",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Servos ad villam ducimus. — Мы ведём рабов к вилле.",
			"test": "<…> Servos ad villam ducimus. — Мы ведём рабов к вилле.",
		},
		{
			"name": "Мы приветствуем мальчиков с похвалой.",
			"id": "latinN_2_AC_p_5c29bfd",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Pueros cum laude salutamus. — Мы приветствуем мальчиков с похвалой.",
			"test": "<…> Pueros cum laude salutamus. — Мы приветствуем мальчиков с похвалой.",
		},
		{
			"name": "Земледельцы ведут коней к воде.",
			"id": "latinN_2_AC_p_7aec35a",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Equos ad aquam ducunt agricolae. — Земледельцы ведут коней к воде.",
			"test": "<…> Equos ad aquam ducunt agricolae. — Земледельцы ведут коней к воде.",
		},
		{
			"name": "Они передают мне большие подарки.",
			"id": "latinN_2_AC_p_67424e82",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Dona magna mihi tradunt. — Они передают мне большие подарки.",
			"test": "<…> Dona magna mihi tradunt. — Они передают мне большие подарки.",
		},
		{
			"name": "Мы учим новые слова.",
			"id": "latinN_2_AC_p_42110406",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Verba nova discimus. — Мы учим новые слова.",
			"test": "<…> Verba nova discimus. — Мы учим новые слова.",
		},
		{
			"name": "Мы посещаем священные храмы.",
			"id": "latinN_2_AC_p_531d72ca",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Templa sacra visitamus. — Мы посещаем священные храмы.",
			"test": "<…> Templa sacra visitamus. — Мы посещаем священные храмы.",
		},
		{
			"name": "Я вижу работающих рабов.",
			"id": "latinN_2_AC_p_22d8cfe0",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Servos laborantes video. — Я вижу работающих рабов.",
			"test": "<…> Servos laborantes video. — Я вижу работающих рабов.",
		},
		{
			"name": "Я приветствую играющих мальчиков.",
			"id": "latinN_2_AC_p_579bb367",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Pueros ludentes saluto. — Я приветствую играющих мальчиков.",
			"test": "<…> Pueros ludentes saluto. — Я приветствую играющих мальчиков.",
		},
		{
			"name": "Они приказывают коням бежать.",
			"id": "latinN_2_AC_p_1de0aca6",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Equos currere iubent. — Они приказывают коням бежать.",
			"test": "<…> Equos currere iubent. — Они приказывают коням бежать.",
		},
		{
			"name": "Ты получаешь маленькие подарки.",
			"id": "latinN_2_AC_p_255316f2",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Dona parva accipis. — Ты получаешь маленькие подарки.",
			"test": "<…> Dona parva accipis. — Ты получаешь маленькие подарки.",
		},
		{
			"name": "Рабы хвалимы господами.",
			"id": "latinN_2_AB_p_41906a77",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Servis a dominis laudantur. — Рабы хвалимы господами.",
			"test": "<…> Servis a dominis laudantur. — Рабы хвалимы господами.",
		},
		{
			"name": "Мальчики ведутся друзьями.",
			"id": "latinN_2_AB_p_4b9af9a9",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Pueri ab amicis ducuntur. — Мальчики ведутся друзьями.",
			"test": "<…> Pueri ab amicis ducuntur. — Мальчики ведутся друзьями.",
		},
		{
			"name": "Кони ухаживаются пастухами.",
			"id": "latinN_2_AB_p_5387f9e0",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Equi a pastoribus curantur. — Кони ухаживаются пастухами.",
			"test": "<…> Equi a pastoribus curantur. — Кони ухаживаются пастухами.",
		},
		{
			"name": "Мы радуемся подаркам, посланным друзьями.",
			"id": "latinN_2_AB_p_6e5e91e4",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Donis ab amicis missis gaudemus. — Мы радуемся подаркам, посланным друзьями.",
			"test": "<…> Donis ab amicis missis gaudemus. — Мы радуемся подаркам, посланным друзьями.",
		},
		{
			"name": "Мы поражены словами, произнесёнными ораторами.",
			"id": "latinN_2_AB_p_2cdf8d8a",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Verbis ab oratoribus pronuntiatis attoniti sumus. — Мы поражены словами, произнесёнными ораторами.",
			"test": "<…> Verbis ab oratoribus pronuntiatis attoniti sumus. — Мы поражены словами, произнесёнными ораторами.",
		},
		{
			"name": "Мы восхищаемся храмами, построенными древними.",
			"id": "latinN_2_AB_p_30946e09",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Templis ab antiquis aedificatis miramur. — Мы восхищаемся храмами, построенными древними.",
			"test": "<…> Templis ab antiquis aedificatis miramur. — Мы восхищаемся храмами, построенными древними.",
		},
		{
			"name": "Мы работаем с верностью рабам (или: «рабы работают с верностью» — зависит от контекста).",
			"id": "latinN_2_AB_p_5cb0d902",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Servis cum fide laboramus. — Мы работаем с верностью рабам (или: «рабы работают с верностью» — зависит от контекста).",
			"test": "<…> Servis cum fide laboramus. — Мы работаем с верностью рабам (или: «рабы работают с верностью» — зависит от контекста).",
		},
		{
			"name": "Мальчики играют с друзьями.",
			"id": "latinN_2_AB_p_46fbb2c1",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Pueri cum amicis ludunt. — Мальчики играют с друзьями.",
			"test": "<…> Pueri cum amicis ludunt. — Мальчики играют с друзьями.",
		},
		{
			"name": "Земледельцы пашут с конями.",
			"id": "latinN_2_AB_p_1698c449",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Agricolae cum equis arant. — Земледельцы пашут с конями.",
			"test": "<…> Agricolae cum equis arant. — Земледельцы пашут с конями.",
		},
		{
			"name": "Мы пользуемся подарками с радостью.",
			"id": "latinN_2_AB_p_5ef04b5",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Donis cum gaudio utimur. — Мы пользуемся подарками с радостью.",
			"test": "<…> Donis cum gaudio utimur. — Мы пользуемся подарками с радостью.",
		},
		{
			"name": "Мы пользуемся словами с осторожностью.",
			"id": "latinN_2_AB_p_5f4da5c3",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Verbis cum cura utimur. — Мы пользуемся словами с осторожностью.",
			"test": "<…> Verbis cum cura utimur. — Мы пользуемся словами с осторожностью.",
		},
		{
			"name": "Мы приближаемся к храмам с почтением.",
			"id": "latinN_2_AB_p_443b7951",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Templis cum reverentia appropinquamus. — Мы приближаемся к храмам с почтением.",
			"test": "<…> Templis cum reverentia appropinquamus. — Мы приближаемся к храмам с почтением.",
		},
		{
			"name": "Мы устали от работы рабов (или: «рабы устали от работы»).",
			"id": "latinN_2_AB_p_14514713",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Servis ab opere defessi sumus. — Мы устали от работы рабов (или: «рабы устали от работы»).",
			"test": "<…> Servis ab opere defessi sumus. — Мы устали от работы рабов (или: «рабы устали от работы»).",
		},
		{
			"name": "Мальчики возвращаются из школ.",
			"id": "latinN_2_AB_p_69663380",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Pueri e ludis reveniunt. — Мальчики возвращаются из школ.",
			"test": "<…> Pueri e ludis reveniunt. — Мальчики возвращаются из школ.",
		},
		{
			"name": "Кони бегут через поле.",
			"id": "latinN_2_AB_p_5b37e0d2",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Equi per campum currunt. — Кони бегут через поле.",
			"test": "<…> Equi per campum currunt. — Кони бегут через поле.",
		},
		{
			"name": "Они радуются подаркам, полученным от матерей.",
			"id": "latinN_2_AB_p_4459eb14",
			"grade": "latin_noun",
			"letters": ["2"],
			"full": "Donis a matribus acceptis gaudent. — Они радуются подаркам, полученным от матерей.",
			"test": "<…> Donis a matribus acceptis gaudent. — Они радуются подаркам, полученным от матерей.",
		}
	);
}
