/*
* Copyright (c) AParovyshnaya 2020-2026
* 
* AParovyshnaya and theirs affiliates make no warranty of any kind
* with regard to this material. 
* 
* AParovyshnaya expressly disclaims all warranties as to the material, express, 
* and implied, including but not limited to the implied warranties of 
* merchantability, fitness for a particular purpose and non-infringement of third 
* party rights. 
* 
* In no event shall AParovyshnaya be liable to you or any other person for any damages, 
* including, without limitation, any direct, indirect, incidental or consequential 
* damages, expenses, lost profits, lost data or other damages arising out of the use, 
* misuse or inability to use the material and any derived software, even if AParovyshnaya, 
* their affiliate or an authorized dealer has been advised of the possibility of such damages. 
* 
*/

export function withLatinNoun1Tests() {
	data.data.push(
		// singular		
		{
			"name": "Виллы",
			"id": "latin1n_villa_np",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Villae sunt magnae. [Виллы большие.]",
			"test": "Vill<…> sunt magnae. [Виллы большие.]"
		},
		{
			"name": "Вода",
			"id": "latin1n_aqua_ns",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aqua fluit. [Вода течёт.]",
			"test": "Aqu<…> fluit. [Вода течёт.]"
		},
		{
			"name": "Земледелец работает в поле.",
			"id": "latinN_1_NO_s_49c2faae",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Agricola in agro laborat. — Земледелец работает в поле.",
			"test": "Agricol<…> in agr<…> laborat. — Земледелец работает в поле.",
		},
		{
			"name": "Поэт пишет стихи.",
			"id": "latinN_1_NO_s_20ad9418",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Poeta carmina scribit. — Поэт пишет стихи.",
			"test": "Poet<…> carmin<…> scribit. — Поэт пишет стихи.",
		},
		{
			"name": "Земля велика.",
			"id": "latinN_1_NO_s_31cefde0",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Terra est magna. — Земля велика.",
			"test": "Terr<…> est magn<…>. — Земля велика.",
		},
		{
			"name": "Вода холодная.",
			"id": "latinN_1_NO_s_439f5b3d",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aqua frigida est. — Вода холодная.",
			"test": "Aqu<…> frigid<…> est. — Вода холодная.",
		},
		{
			"name": "Девочка поёт.",
			"id": "latinN_1_NO_s_1d56ce6a",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Puella cantat. — Девочка поёт.",
			"test": "Puell<…> cantat. — Девочка поёт.",
		},
		{
			"name": "Звезда светит.",
			"id": "latinN_1_NO_s_5197848c",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Stella lucet. — Звезда светит.",
			"test": "Stell<…> lucet. — Звезда светит.",
		},
		{
			"name": "Вилла земледельца прекрасна.",
			"id": "latinN_1_GE_s_17f052a3",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Villa agricolae pulchra est. — Вилла земледельца прекрасна.",
			"test": "Vill<…> agricol<…> pulchr<…> est. — Вилла земледельца прекрасна.",
		},
		{
			"name": "Книга поэта известна.",
			"id": "latinN_1_GE_s_2e0fa5d3",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Liber poetae notus est. — Книга поэта известна.",
			"test": "Liber poet<…> notus est. — Книга поэта известна.",
		},
		{
			"name": "Цвет воды голубой.",
			"id": "latinN_1_GE_s_5010be6",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Color aquae caeruleus est. — Цвет воды голубой.",
			"test": "Color aqu<…> caeruleus est. — Цвет воды голубой.",
		},
		{
			"name": "Название земли — Греция.",
			"id": "latinN_1_GE_s_685f4c2e",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Nomen terrae Graecia est. — Название земли — Греция.",
			"test": "Nomen terr<…> Graecia est. — Название земли — Греция.",
		},
		{
			"name": "Мать девочки очень мудрая.",
			"id": "latinN_1_GE_s_7daf6ecc",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Mater puellae sapientissima est. — Мать девочки очень мудрая.",
			"test": "Mater puell<…> sapientissima est. — Мать девочки очень мудрая.",
		},
		{
			"name": "Свет звезды яркий.",
			"id": "latinN_1_GE_s_2e5d6d97",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Lux stellae clara est. — Свет звезды яркий.",
			"test": "Lux stell<…> clara est. — Свет звезды яркий.",
		},
		{
			"name": "Семья земледельца большая.",
			"id": "latinN_1_GE_s_238e0d81",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Familia agricolae magna est. — Семья земледельца большая.",
			"test": "Familia agricol<…> magna est. — Семья земледельца большая.",
		},
		{
			"name": "Стихи поэта прекрасны.",
			"id": "latinN_1_GE_s_31221be2",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Versus poetae pulchri sunt. — Стихи поэта прекрасны.",
			"test": "Versus poet<…> pulchri sunt. — Стихи поэта прекрасны.",
		},
		{
			"name": "Добродетель девочки восхваляется.",
			"id": "latinN_1_GE_s_377dca04",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Virtus puellae laudatur. — Добродетель девочки восхваляется.",
			"test": "Virtus puell<…> laudatur. — Добродетель девочки восхваляется.",
		},
		{
			"name": "Брат девочки — юноша.",
			"id": "latinN_1_GE_s_728938a9",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Frater puellae iuvenis est. — Брат девочки — юноша.",
			"test": "Frater puell<…> iuvenis est. — Брат девочки — юноша.",
		},
		{
			"name": "Начало земли неопределённо.",
			"id": "latinN_1_GE_s_21b8d17c",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Initium terrae incertum est. — Начало земли неопределённо.",
			"test": "Initium terr<…> incertum est. — Начало земли неопределённо.",
		},
		{
			"name": "Название воды — Тибр.",
			"id": "latinN_1_GE_s_6433a2",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Nomen aquae Tiberis est. — Название воды — Тибр.",
			"test": "Nomen aqu<…> Tiberis est. — Название воды — Тибр.",
		},
		{
			"name": "Дом земледельца находится возле леса.",
			"id": "latinN_1_GE_s_5910e440",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Domus agricolae prope silvam est. — Дом земледельца находится возле леса.",
			"test": "Domus agricol<…> prope silvam est. — Дом земледельца находится возле леса.",
		},
		{
			"name": "Стихи поэта находятся в книге.",
			"id": "latinN_1_GE_s_6267c3bb",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Carmina poetae in libro sunt. — Стихи поэта находятся в книге.",
			"test": "Carmina poet<…> in libro sunt. — Стихи поэта находятся в книге.",
		},
		{
			"name": "Подруга девочки живёт в Риме.",
			"id": "latinN_1_GE_s_533ddba",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Amica puellae Romae habitat. — Подруга девочки живёт в Риме.",
			"test": "Amica puell<…> Romae habitat. — Подруга девочки живёт в Риме.",
		},
		{
			"name": "Знак звезды виден на небе.",
			"id": "latinN_1_GE_s_246b179d",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Signum stellae in caelo videtur. — Знак звезды виден на небе.",
			"test": "Signum stell<…> in caelo videtur. — Знак звезды виден на небе.",
		},
		{
			"name": "Я посылаю дары земледельцу.",
			"id": "latinN_1_DA_s_7a07c5b4",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Dona agricolae mitto. — Я посылаю дары земледельцу.",
			"test": "Dona agricol<…> mitto. — Я посылаю дары земледельцу.",
		},
		{
			"name": "Я даю книги поэту.",
			"id": "latinN_1_DA_s_26a1ab54",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Libros poetae do. — Я даю книги поэту.",
			"test": "Libros poet<…> do. — Я даю книги поэту.",
		},
		{
			"name": "Вода даётся земле.",
			"id": "latinN_1_DA_s_3d646c37",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aqua terrae datur. — Вода даётся земле.",
			"test": "Aqua terr<…> datur. — Вода даётся земле.",
		},
		{
			"name": "Я дарю розы девочке.",
			"id": "latinN_1_DA_s_41cf53f9",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Rosas puellae dono. — Я дарю розы девочке.",
			"test": "Ros<…> puell<…> dono. — Я дарю розы девочке.",
		},
		{
			"name": "Мир для девочки — наилучший.",
			"id": "latinN_1_DA_s_5a10411",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Pax puellae optima est. — Мир для девочки — наилучший.",
			"test": "Pax puell<…> optima est. — Мир для девочки — наилучший.",
		},
		{
			"name": "Помощь звезды не нужна.",
			"id": "latinN_1_DA_s_2ef1e4fa",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Auxilium stellae non opus est. — Помощь звезды не нужна.",
			"test": "Auxilium stell<…> non opus est. — Помощь звезды не нужна.",
		},
		{
			"name": "Дар земледельцу маленький.",
			"id": "latinN_1_DA_s_306a30c7",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Donum agricolae parvum est. — Дар земледельцу маленький.",
			"test": "Donum agricol<…> parvum est. — Дар земледельцу маленький.",
		},
		{
			"name": "Совет поэта очень полезен.",
			"id": "latinN_1_DA_s_b81eda8",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Consilium poetae utilissimum est. — Совет поэта очень полезен.",
			"test": "Consilium poet<…> utilissimum est. — Совет поэта очень полезен.",
		},
		{
			"name": "Помощь девочке необходима.",
			"id": "latinN_1_DA_s_68de145",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Auxilium puellae necessarium est. — Помощь девочке необходима.",
			"test": "Auxilium puell<…> necessarium est. — Помощь девочке необходима.",
		},
		{
			"name": "Книга девочки новая.",
			"id": "latinN_1_DA_s_27fa135a",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Liber puellae novus est. — Книга девочки новая.",
			"test": "Liber puell<…> novus est. — Книга девочки новая.",
		},
		{
			"name": "Мы желаем здоровья земле.",
			"id": "latinN_1_DA_s_46f7f36a",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Salutem terrae optamus. — Мы желаем здоровья земле.",
			"test": "Salutem terr<…> optamus. — Мы желаем здоровья земле.",
		},
		{
			"name": "Я дарю розы воде (как символу).",
			"id": "latinN_1_DA_s_421faab1",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Rosas aquae dono. — Я дарю розы воде (как символу).",
			"test": "Rosas aqu<…> dono. — Я дарю розы воде (как символу).",
		},
		{
			"name": "Слова поэта говорятся ученикам.",
			"id": "latinN_1_DA_s_2b71fc7e",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Verba poetae discipulis dicuntur. — Слова поэта говорятся ученикам.",
			"test": "Verba poet<…> discipulis dicuntur. — Слова поэта говорятся ученикам.",
		},
		{
			"name": "Награда земледельцу большая.",
			"id": "latinN_1_DA_s_5ce65a89",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Praemium agricolae magnum est. — Награда земледельцу большая.",
			"test": "Praemium agricol<…> magnum est. — Награда земледельцу большая.",
		},
		{
			"name": "Письмо девочке отправлено другом.",
			"id": "latinN_1_DA_s_25f38edc",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Epistula puellae ab amico missa est. — Письмо девочке отправлено другом.",
			"test": "Epistula puell<…> ab amico missa est. — Письмо девочке отправлено другом.",
		},
		{
			"name": "Звезде возносятся благодарности.",
			"id": "latinN_1_DA_s_1a86f2f1",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Gratiae stellae aguntur. — Звезде возносятся благодарности.",
			"test": "Gratiae stell<…> aguntur. — Звезде возносятся благодарности.",
		},
		{
			"name": "Я вижу земледельца в поле.",
			"id": "latinN_1_AC_s_3eb07fd3",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Agricolam in agro video. — Я вижу земледельца в поле.",
			"test": "Agricol<…> in agr<…> video. — Я вижу земледельца в поле.",
		},
		{
			"name": "Я хвалю поэта.",
			"id": "latinN_1_AC_s_506c589e",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Poetam laudo. — Я хвалю поэта.",
			"test": "Poet<…> laudo. — Я хвалю поэта.",
		},
		{
			"name": "Мы пьём воду.",
			"id": "latinN_1_AC_s_69d0a921",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aquam bibimus. — Мы пьём воду.",
			"test": "Aqu<…> bibimus. — Мы пьём воду.",
		},
		{
			"name": "Мы любим землю.",
			"id": "latinN_1_AC_s_446cdf90",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Terram amamus. — Мы любим землю.",
			"test": "Terr<…> amamus. — Мы любим землю.",
		},
		{
			"name": "Я зову девочку.",
			"id": "latinN_1_AC_s_799f7e29",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Puellam voco. — Я зову девочку.",
			"test": "Puell<…> voco. — Я зову девочку.",
		},
		{
			"name": "Я вижу звезду на небе.",
			"id": "latinN_1_AC_s_4b85612c",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Stellam in caelo video. — Я вижу звезду на небе.",
			"test": "Stell<…> in cael<…> video. — Я вижу звезду на небе.",
		},
		{
			"name": "Я вижу земледельца на дороге.",
			"id": "latinN_1_AC_s_277050dc",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Agricolam in via video. — Я вижу земледельца на дороге.",
			"test": "Agricol<…> in vi<…> video. — Я вижу земледельца на дороге.",
		},
		{
			"name": "Я слышал поэта на форуме.",
			"id": "latinN_1_AC_s_5c29bfd",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Poetam in foro audivi. — Я слышал поэта на форуме.",
			"test": "Poet<…> in for<…> audivi. — Я слышал поэта на форуме.",
		},
		{
			"name": "Он пьёт холодную воду.",
			"id": "latinN_1_AC_s_7aec35a",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aquam frigidam bibit. — Он пьёт холодную воду.",
			"test": "Aqu<…> frigid<…> bibit. — Он пьёт холодную воду.",
		},
		{
			"name": "Мы находим новую землю.",
			"id": "latinN_1_AC_s_67424e82",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Terram novam invenimus. — Мы находим новую землю.",
			"test": "Terr<…> nov<…> invenimus. — Мы находим новую землю.",
		},
		{
			"name": "Я позвал девочку в саду.",
			"id": "latinN_1_AC_s_42110406",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Puellam in horto vocavi. — Я позвал девочку в саду.",
			"test": "Puell<…> in hort<…> vocavi. — Я позвал девочку в саду.",
		},
		{
			"name": "Мы наблюдаем большую звезду на небе.",
			"id": "latinN_1_AC_s_531d72ca",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Stellam magnam in caelo spectamus. — Мы наблюдаем большую звезду на небе.",
			"test": "Stell<…> magn<…> in cael<…> spectamus. — Мы наблюдаем большую звезду на небе.",
		},
		{
			"name": "Мы ведём земледельца к вилле.",
			"id": "latinN_1_AC_s_22d8cfe0",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Agricolam ad villam ducimus. — Мы ведём земледельца к вилле.",
			"test": "Agricol<…> ad vill<…> ducimus. — Мы ведём земледельца к вилле.",
		},
		{
			"name": "Мы приветствуем поэта с похвалой.",
			"id": "latinN_1_AC_s_579bb367",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Poetam cum laude salutamus. — Мы приветствуем поэта с похвалой.",
			"test": "Poet<…> cum laude salutamus. — Мы приветствуем поэта с похвалой.",
		},
		{
			"name": "Мы ставим воду в амфору.",
			"id": "latinN_1_AC_s_1de0aca6",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aquam in amphoram ponimus. — Мы ставим воду в амфору.",
			"test": "Aqu<…> in amphoram ponimus. — Мы ставим воду в амфору.",
		},
		{
			"name": "Я повёл девочку в школу.",
			"id": "latinN_1_AC_s_255316f2",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Puellam ad ludum duxi. — Я повёл девочку в школу.",
			"test": "Puell<…> ad ludum duxi. — Я повёл девочку в школу.",
		},
		{
			"name": "Земледелец гуляет с друзьями.",
			"id": "latinN_1_AB_s_41906a77",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Agricola cum amicis ambulat. — Земледелец гуляет с друзьями.",
			"test": "Agricol<…> cum amic<…> ambulat. — Земледелец гуляет с друзьями.",
		},
		{
			"name": "Поэт уходит из города.",
			"id": "latinN_1_AB_s_4b9af9a9",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Poeta ab urbe discedit. — Поэт уходит из города.",
			"test": "Poet<…> ab urb<…> discedit. — Поэт уходит из города.",
		},
		{
			"name": "Вода идёт из тучи.",
			"id": "latinN_1_AB_s_5387f9e0",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aqua ab nube venit. — Вода идёт из тучи.",
			"test": "Aqu<…> ab nub<…> venit. — Вода идёт из тучи.",
		},
		{
			"name": "Земля освещается солнцем.",
			"id": "latinN_1_AB_s_6e5e91e4",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Terra a sole illustratur. — Земля освещается солнцем.",
			"test": "Terr<…> a sol<…> illustratur. — Земля освещается солнцем.",
		},
		{
			"name": "Девочка живёт с матерью.",
			"id": "latinN_1_AB_s_2cdf8d8a",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Puella cum matre habitat. — Девочка живёт с матерью.",
			"test": "Puell<…> cum matr<…> habitat. — Девочка живёт с матерью.",
		},
		{
			"name": "Звезда светит ночью.",
			"id": "latinN_1_AB_s_30946e09",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Stella nocte lucet. — Звезда светит ночью.",
			"test": "Stell<…> noct<…> lucet. — Звезда светит ночью.",
		},
		{
			"name": "Земледелец гуляет с собаками.",
			"id": "latinN_1_AB_s_5cb0d902",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Agricola cum canibus ambulat. — Земледелец гуляет с собаками.",
			"test": "Agricol<…> cum canibus ambulat. — Земледелец гуляет с собаками.",
		},
		{
			"name": "Поэт восхваляется друзьями.",
			"id": "latinN_1_AB_s_46fbb2c1",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Poeta ab amicis laudatur. — Поэт восхваляется друзьями.",
			"test": "Poet<…> ab amic<…> laudatur. — Поэт восхваляется друзьями.",
		},
		{
			"name": "Вода течёт из источника.",
			"id": "latinN_1_AB_s_1698c449",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aqua ab fonte manat. — Вода течёт из источника.",
			"test": "Aqu<…> ab font<…> manat. — Вода течёт из источника.",
		},
		{
			"name": "Земля покрывается облаками.",
			"id": "latinN_1_AB_s_5ef04b5",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Terra a nubibus tegitur. — Земля покрывается облаками.",
			"test": "Terr<…> a nubibus tegitur. — Земля покрывается облаками.",
		},
		{
			"name": "Девочка играет с сестрой.",
			"id": "latinN_1_AB_s_5f4da5c3",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Puella cum sorore ludit. — Девочка играет с сестрой.",
			"test": "Puell<…> cum sorore ludit. — Девочка играет с сестрой.",
		},
		{
			"name": "Звезда не затемняется луной.",
			"id": "latinN_1_AB_s_443b7951",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Stella ab luna non obscuratur. — Звезда не затемняется луной.",
			"test": "Stell<…> ab luna non obscuratur. — Звезда не затемняется луной.",
		},
		{
			"name": "Земледелец работает с плугом.",
			"id": "latinN_1_AB_s_14514713",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Agricola cum aratro laborat. — Земледелец работает с плугом.",
			"test": "Agricol<…> cum aratro laborat. — Земледелец работает с плугом.",
		},
		{
			"name": "Мать гуляет с девочкой.",
			"id": "latinN_1_AB_s_14514713_1",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Mater cum puella ambulat. — Мать гуляет с девочкой.",
			"test": "Mater cum puell<…> ambulat. — Мать гуляет с девочкой."
		},
		{
			"name": "Поэт поёт с лирой.",
			"id": "latinN_1_AB_s_69663380",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Poeta cum lyra cantat. — Поэт поёт с лирой.",
			"test": "Poet<…> cum lyra cantat. — Поэт поёт с лирой.",
		},
		{
			"name": "Горячая вода идёт из терм.",
			"id": "latinN_1_AB_s_5b37e0d2",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aqua calida ab thermis venit. — Горячая вода идёт из терм.",
			"test": "Aqu<…> calid<…> ab thermis venit. — Горячая вода идёт из терм.",
		},
		{
			"name": "Девочка учится у учителя.",
			"id": "latinN_1_AB_s_4459eb14",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Puella ab magistro discit. — Девочка учится у учителя.",
			"test": "Puell<…> ab magistr<…> discit. — Девочка учится у учителя.",
		},
		// plural
		{
			"name": "Земледельцы работают в полях.",
			"id": "latinN_1_NO_p_49c2faae",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Agricolae in agris laborant. — Земледельцы работают в полях.",
			"test": "Agricol<…> in agr<…> laborant. — Земледельцы работают в полях.",
		},
		{
			"name": "Поэты пишут стихи.",
			"id": "latinN_1_NO_p_20ad9418",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Poetae carmina scribunt. — Поэты пишут стихи.",
			"test": "Poet<…> carmin<…> scribunt. — Поэты пишут стихи.",
		},
		{
			"name": "Земли прекрасны.",
			"id": "latinN_1_NO_p_31cefde0",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Terrae sunt pulchrae. — Земли прекрасны.",
			"test": "Terr<…> sunt pulchr<…>. — Земли прекрасны.",
		},
		{
			"name": "Воды холодные.",
			"id": "latinN_1_NO_p_439f5b3d",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aquae frigidae sunt. — Воды холодные.",
			"test": "Aqu<…> frigid<…> sunt. — Воды холодные.",
		},
		{
			"name": "Девочки играют в саду.",
			"id": "latinN_1_NO_p_1d56ce6a",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Puellae in horto ludunt. — Девочки играют в саду.",
			"test": "Puell<…> in hort<…> ludunt. — Девочки играют в саду.",
		},
		{
			"name": "Звёзды светят на небе.",
			"id": "latinN_1_NO_p_5197848c",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Stellae in caelo lucent. — Звёзды светят на небе.",
			"test": "Stell<…> in cael<…> lucent. — Звёзды светят на небе.",
		},
		{
			"name": "Семьи земледельцев большие.",
			"id": "latinN_1_GE_p_17f052a3",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Familiae agricolarum magnae sunt. — Семьи земледельцев большие.",
			"test": "Famili<…> agricol<…> magnae sunt. — Семьи земледельцев большие.",
		},
		{
			"name": "Стихи поэтов прекрасны.",
			"id": "latinN_1_GE_p_2e0fa5d3",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Versus poetarum pulchri sunt. — Стихи поэтов прекрасны.",
			"test": "Versus poet<…> pulchri sunt. — Стихи поэтов прекрасны.",
		},
		{
			"name": "Добродетели девочек восхваляются.",
			"id": "latinN_1_GE_p_5010be6",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Virtutes puellarum laudantur. — Добродетели девочек восхваляются.",
			"test": "Virtutes puell<…> laudantur. — Добродетели девочек восхваляются.",
		},
		{
			"name": "Названия земель длинные.",
			"id": "latinN_1_GE_p_685f4c2e",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Nomina terrarum longa sunt. — Названия земель длинные.",
			"test": "Nomina terr<…> longa sunt. — Названия земель длинные.",
		},
		{
			"name": "Подруги девочек живут в Риме.",
			"id": "latinN_1_GE_p_7daf6ecc",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Amicae puellarum Romae habitant. — Подруги девочек живут в Риме.",
			"test": "Amicae puell<…> Romae habitant. — Подруги девочек живут в Риме.",
		},
		{
			"name": "Знаки звёзд видны на небе.",
			"id": "latinN_1_GE_p_2e5d6d97",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Signa stellarum in caelo videntur. — Знаки звёзд видны на небе.",
			"test": "Signa stell<…> in caelo videntur. — Знаки звёзд видны на небе.",
		},
		{
			"name": "Дома земледельцев находятся возле лесов.",
			"id": "latinN_1_GE_p_238e0d81",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Domus agricolarum prope silvas sunt. — Дома земледельцев находятся возле лесов.",
			"test": "Domus agricol<…> prope silvas sunt. — Дома земледельцев находятся возле лесов.",
		},
		{
			"name": "Стихи поэтов находятся в книгах.",
			"id": "latinN_1_GE_p_31221be2",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Carmina poetarum in libris sunt. — Стихи поэтов находятся в книгах.",
			"test": "Carmina poet<…> in libr<…> sunt. — Стихи поэтов находятся в книгах.",
		},
		{
			"name": "Начала земель неопределённые.",
			"id": "latinN_1_GE_p_377dca04",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Initia terrarum incerta sunt. — Начала земель неопределённые.",
			"test": "Initia terr<…> incerta sunt. — Начала земель неопределённые.",
		},
		{
			"name": "Название вод — Тибр.",
			"id": "latinN_1_GE_p_728938a9",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Nomen aquarum Tiberis est. — Название вод — Тибр.",
			"test": "Nomen aqu<…> Tiberis est. — Название вод — Тибр.",
		},
		{
			"name": "Дары земледельцев маленькие.",
			"id": "latinN_1_GE_p_21b8d17c",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Dona agricolarum parva sunt. — Дары земледельцев маленькие.",
			"test": "Dona agricol<…> parva sunt. — Дары земледельцев маленькие.",
		},
		{
			"name": "Советы поэтов очень полезны.",
			"id": "latinN_1_GE_p_6433a2",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Consilia poetarum utilissima sunt. — Советы поэтов очень полезны.",
			"test": "Consilia poet<…> utilissima sunt. — Советы поэтов очень полезны.",
		},
		{
			"name": "Помощи девочек необходимы.",
			"id": "latinN_1_GE_p_5910e440",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Auxilia puellarum necessaria sunt. — Помощи девочек необходимы.",
			"test": "Auxilia puell<…> necessaria sunt. — Помощи девочек необходимы.",
		},
		{
			"name": "Книги девочек новые.",
			"id": "latinN_1_GE_p_6267c3bb",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Libri puellarum novi sunt. — Книги девочек новые.",
			"test": "Libri puell<…> novi sunt. — Книги девочек новые.",
		},
		{
			"name": "Здоровья земель желают.",
			"id": "latinN_1_GE_p_533ddba",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Salutes terrarum optantur. — Здоровья земель желают.",
			"test": "Salutes terr<…> optantur. — Здоровья земель желают.",
		},
		{
			"name": "Розы дарятся водам (как символу).",
			"id": "latinN_1_GE_p_246b179d",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Rosae aquarum donantur. — Розы дарятся водам (как символу).",
			"test": "Rosae aqu<…> donantur. — Розы дарятся водам (как символу).",
		},
		{
			"name": "Дар земледельцам маленький.",
			"id": "latinN_1_DA_p_7a07c5b4",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Donum agricolis parvum est. — Дар земледельцам маленький.",
			"test": "Donum agricol<…> parvum est. — Дар земледельцам маленький.",
		},
		{
			"name": "Совет поэтам очень полезен.",
			"id": "latinN_1_DA_p_26a1ab54",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Consilium poetis utilissimum est. — Совет поэтам очень полезен.",
			"test": "Consilium poet<…> utilissimum est. — Совет поэтам очень полезен.",
		},
		{
			"name": "Помощь девочкам необходима.",
			"id": "latinN_1_DA_p_3d646c37",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Auxilium puellis necessarium est. — Помощь девочкам необходима.",
			"test": "Auxilium puell<…> necessarium est. — Помощь девочкам необходима.",
		},
		{
			"name": "Книга девочкам новая.",
			"id": "latinN_1_DA_p_41cf53f9",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Liber puellis novus est. — Книга девочкам новая.",
			"test": "Liber puell<…> novus est. — Книга девочкам новая.",
		},
		{
			"name": "Мы желаем здоровья землям.",
			"id": "latinN_1_DA_p_5a10411",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Salutem terris optamus. — Мы желаем здоровья землям.",
			"test": "Salutem terr<…> optamus. — Мы желаем здоровья землям.",
		},
		{
			"name": "Я дарю розы водам.",
			"id": "latinN_1_DA_p_2ef1e4fa",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Rosas aquis dono. — Я дарю розы водам.",
			"test": "Rosas aqu<…> dono. — Я дарю розы водам.",
		},
		{
			"name": "Слова поэтов говорятся ученикам.",
			"id": "latinN_1_DA_p_306a30c7",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Verba poetis discipulis dicuntur. — Слова поэтов говорятся ученикам.",
			"test": "Verba poet<…> discipulis dicuntur. — Слова поэтов говорятся ученикам.",
		},
		{
			"name": "Награды земледельцам большие.",
			"id": "latinN_1_DA_p_b81eda8",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Praemia agricolis magna sunt. — Награды земледельцам большие.",
			"test": "Praemia agricol<…> magna sunt. — Награды земледельцам большие.",
		},
		{
			"name": "Письма девочкам отправлены друзьями.",
			"id": "latinN_1_DA_p_68de145",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Epistulae puellis ab amicis missae sunt. — Письма девочкам отправлены друзьями.",
			"test": "Epistulae puell<…> ab amicis missae sunt. — Письма девочкам отправлены друзьями.",
		},
		{
			"name": "Звёздам возносятся благодарности.",
			"id": "latinN_1_DA_p_27fa135a",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Gratiae stellis aguntur. — Звёздам возносятся благодарности.",
			"test": "Gratiae stell<…> aguntur. — Звёздам возносятся благодарности.",
		},
		{
			"name": "Поэтам даются награды.",
			"id": "latinN_1_DA_p_46f7f36a",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Praemia poetis dantur. — Поэтам даются награды.",
			"test": "Praemia poet<…> dantur. — Поэтам даются награды.",
		},
		{
			"name": "Я посылаю дар девочкам.",
			"id": "latinN_1_DA_p_421faab1",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Donum puellis mitto. — Я посылаю дар девочкам.",
			"test": "Donum puell<…> mitto. — Я посылаю дар девочкам.",
		},
		{
			"name": "Советы земледельцам полезны.",
			"id": "latinN_1_DA_p_2b71fc7e",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Consilia agricolis utilia sunt. — Советы земледельцам полезны.",
			"test": "Consilia agricol<…> utilia sunt. — Советы земледельцам полезны.",
		},
		{
			"name": "Помощи землям необходимы.",
			"id": "latinN_1_DA_p_5ce65a89",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Auxilia terris necessaria sunt. — Помощи землям необходимы.",
			"test": "Auxilia terr<…> necessaria sunt. — Помощи землям необходимы.",
		},
		{
			"name": "Книги звёздам не нужны.",
			"id": "latinN_1_DA_p_25f38edc",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Libri stellis non opus sunt. — Книги звёздам не нужны.",
			"test": "Libri stell<…> non opus sunt. — Книги звёздам не нужны.",
		},
		{
			"name": "Мы говорим слова водам.",
			"id": "latinN_1_DA_p_1a86f2f1",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Verba aquis dicimus. — Мы говорим слова водам.",
			"test": "Verba aqu<…> dicimus. — Мы говорим слова водам.",
		},
		{
			"name": "Я вижу земледельцев на дорогах.",
			"id": "latinN_1_AC_p_3eb07fd3",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Agricolas in viis video. — Я вижу земледельцев на дорогах.",
			"test": "Agricolas in vi<…> video. — Я вижу земледельцев на дорогах.",
		},
		{
			"name": "Я слышу поэтов на форумах.",
			"id": "latinN_1_AC_p_506c589e",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Poetas in foris audio. — Я слышу поэтов на форумах.",
			"test": "Poet<…> in for<…> audio. — Я слышу поэтов на форумах.",
		},
		{
			"name": "Мы пьём холодные воды.",
			"id": "latinN_1_AC_p_69d0a921",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aquas frigidas bibimus. — Мы пьём холодные воды.",
			"test": "Aqu<…> frigid<…> bibimus. — Мы пьём холодные воды.",
		},
		{
			"name": "Мы находим новые земли.",
			"id": "latinN_1_AC_p_446cdf90",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Terras novas invenimus. — Мы находим новые земли.",
			"test": "Terr<…> nov<…> invenimus. — Мы находим новые земли.",
		},
		{
			"name": "Я позвал девочек в садах.",
			"id": "latinN_1_AC_p_799f7e29",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Puellas in hortis vocavi. — Я позвал девочек в садах.",
			"test": "Puell<…> in hort<…> vocavi. — Я позвал девочек в садах.",
		},
		{
			"name": "Мы наблюдаем большие звёзды на небе.",
			"id": "latinN_1_AC_p_4b85612c",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Stellas magnas in caelo spectamus. — Мы наблюдаем большие звёзды на небе.",
			"test": "Stell<…> magn<…> in caelo spectamus. — Мы наблюдаем большие звёзды на небе.",
		},
		{
			"name": "Мы ведём земледельцев к виллам.",
			"id": "latinN_1_AC_p_277050dc",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Agricolas ad villas ducimus. — Мы ведём земледельцев к виллам.",
			"test": "Agricol<…> ad vill<…> ducimus. — Мы ведём земледельцев к виллам.",
		},
		{
			"name": "Мы приветствуем поэтов с похвалой.",
			"id": "latinN_1_AC_p_5c29bfd",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Poetas cum laude salutamus. — Мы приветствуем поэтов с похвалой.",
			"test": "Poet<…> cum laud<…> salutamus. — Мы приветствуем поэтов с похвалой.",
		},
		{
			"name": "Мы ставим воды в амфоры.",
			"id": "latinN_1_AC_p_7aec35a",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aquas in amphoras ponimus. — Мы ставим воды в амфоры.",
			"test": "Aqu<…> in amphor<…> ponimus. — Мы ставим воды в амфоры.",
		},
		{
			"name": "Я повёл девочек в школы.",
			"id": "latinN_1_AC_p_67424e82",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Puellas ad ludos duxi. — Я повёл девочек в школы.",
			"test": "Puell<…> ad lud<…> duxi. — Я повёл девочек в школы.",
		},
		{
			"name": "Мы видели звёзды ночью.",
			"id": "latinN_1_AC_p_42110406",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Stellas nocte vidimus. — Мы видели звёзды ночью.",
			"test": "Stell<…> noct<…> vidimus. — Мы видели звёзды ночью.",
		},
		{
			"name": "Я вижу работающих земледельцев.",
			"id": "latinN_1_AC_p_531d72ca",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Agricolas laborantes video. — Я вижу работающих земледельцев.",
			"test": "Agricol<…> laborant<…> video. — Я вижу работающих земледельцев.",
		},
		{
			"name": "Я слышал поющих поэтов.",
			"id": "latinN_1_AC_p_22d8cfe0",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Poetas cantantes audivi. — Я слышал поющих поэтов.",
			"test": "Poet<…> cantant<…> audivi. — Я слышал поющих поэтов.",
		},
		{
			"name": "Я приветствую смеющихся девочек.",
			"id": "latinN_1_AC_p_579bb367",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Puellas ridentes saluto. — Я приветствую смеющихся девочек.",
			"test": "Puell<…> rident<…> saluto. — Я приветствую смеющихся девочек.",
		},
		{
			"name": "Мы наблюдаем текущие воды.",
			"id": "latinN_1_AC_p_1de0aca6",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aquas fluentes spectamus. — Мы наблюдаем текущие воды.",
			"test": "Aqu<…> fluent<…> spectamus. — Мы наблюдаем текущие воды.",
		},
		{
			"name": "Мы любим вспаханные земли.",
			"id": "latinN_1_AC_p_255316f2",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Terras aratas amamus. — Мы любим вспаханные земли.",
			"test": "Terr<…> arat<…> amamus. — Мы любим вспаханные земли.",
		},
		{
			"name": "Земледельцы гуляют с собаками.",
			"id": "latinN_1_AB_p_41906a77",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Agricolae cum canibus ambulant. — Земледельцы гуляют с собаками.",
			"test": "Agricol<…> cum canib<…> ambulant. — Земледельцы гуляют с собаками.",
		},
		{
			"name": "Поэты восхваляются друзьями.",
			"id": "latinN_1_AB_p_4b9af9a9",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Poetae ab amicis laudantur. — Поэты восхваляются друзьями.",
			"test": "Poet<…> ab amic<…> laudantur. — Поэты восхваляются друзьями.",
		},
		{
			"name": "Воды текут из источников.",
			"id": "latinN_1_AB_p_5387f9e0",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aquae ab fontibus manant. — Воды текут из источников.",
			"test": "Aqu<…> ab font<…> manant. — Воды текут из источников.",
		},
		{
			"name": "Земли покрываются облаками.",
			"id": "latinN_1_AB_p_6e5e91e4",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Terrae a nubibus teguntur. — Земли покрываются облаками.",
			"test": "Terr<…> a nub<…> teguntur. — Земли покрываются облаками.",
		},
		{
			"name": "Девочки играют с сёстрами.",
			"id": "latinN_1_AB_p_2cdf8d8a",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Puellae cum sororibus ludunt. — Девочки играют с сёстрами.",
			"test": "Puell<…> cum soror<…> ludunt. — Девочки играют с сёстрами.",
		},
		{
			"name": "Звёзды не затемняются луной.",
			"id": "latinN_1_AB_p_30946e09",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Stellae ab luna non obscurantur. — Звёзды не затемняются луной.",
			"test": "Stell<…> ab lun<…> non obscurantur. — Звёзды не затемняются луной.",
		},
		{
			"name": "Земледельцы работают с плугами.",
			"id": "latinN_1_AB_p_5cb0d902",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Agricolae cum aratris laborant. — Земледельцы работают с плугами.",
			"test": "Agricol<…> cum aratr<…> laborant. — Земледельцы работают с плугами.",
		},
		{
			"name": "Поэты поют с лирами.",
			"id": "latinN_1_AB_p_46fbb2c1",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Poetae cum lyris cantant. — Поэты поют с лирами.",
			"test": "Poet<…> cum lyr<…> cantant. — Поэты поют с лирами.",
		},
		{
			"name": "Горячие воды идут из терм.",
			"id": "latinN_1_AB_p_1698c449",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aquae calidae ab thermis veniunt. — Горячие воды идут из терм.",
			"test": "Aqu<…> calid<…> ab ther<…>s veniunt. — Горячие воды идут из терм.",
		},
		{
			"name": "Девочки учатся у учителей.",
			"id": "latinN_1_AB_p_5ef04b5",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Puellae ab magistris discunt. — Девочки учатся у учителей.",
			"test": "Puell<…> ab magistr<…> discunt. — Девочки учатся у учителей.",
		},
		{
			"name": "Земледельцы уходят от земель.",
			"id": "latinN_1_AB_p_5f4da5c3",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Agricolae a terris discedunt. — Земледельцы уходят от земель.",
			"test": "Agricol<…> a terr<…> discedunt. — Земледельцы уходят от земель.",
		},
		{
			"name": "Поэты вернулись со славой.",
			"id": "latinN_1_AB_p_443b7951",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Poetae cum gloria redierunt. — Поэты вернулись со славой.",
			"test": "Poet<…> cum glori<…> redierunt. — Поэты вернулись со славой.",
		},
		{
			"name": "Девочки приходят из садов.",
			"id": "latinN_1_AB_p_14514713",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Puellae ex hortis veniunt. — Девочки приходят из садов.",
			"test": "Puella<…>ex hort<…> veniunt. — Девочки приходят из садов.",
		},
		{
			"name": "Воды текут по дорогам.",
			"id": "latinN_1_AB_p_69663380",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Aquae per vias fluunt. — Воды текут по дорогам.",
			"test": "Aqu<…> per vi<…> fluunt. — Воды текут по дорогам.",
		},
		{
			"name": "Земледельцы устали от работы.",
			"id": "latinN_1_AB_p_4459eb14",
			"grade": "latin_noun",
			"letters": ["1"],
			"full": "Agricolae ab opere defessi sunt. — Земледельцы устали от работы.",
			"test": "Agricol<…> ab oper<…> defessi sunt. — Земледельцы устали от работы.",
		}
	);
}
